### ISSUE TITLE
[feature] shell completion

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#1]
Add completion on commands project names and tags may be useful.

**Comment by SpotlightKid** [comment]
Here's a bash completion script. `source` it or put it in `/etc/bash_completion.d`. This completes `watson` commands, command options, command names for the `help` command and projects and tags for the `start` command. It doesn't complete projects or tags for the `-p` and `-T` options of `log` and `report` yet. Another nice feature would be to complete frame ids for the `remove` and `edit` commands.

This is my first bash completion script, so maybe there are better way to do this...

```
# Bash completion suppoort for watson

_watson_complete () {
    local cur cmd commands projects tags

    commands='cancel config edit help log projects remove report start status stop sync tags'

    cur=${COMP_WORDS[COMP_CWORD]}
    cmd=${COMP_WORDS[1]}

    case ${COMP_CWORD} in
        1)
            COMPREPLY=($(compgen -W "$commands" -- "$cur" )) ;;
        *)
            case "${cmd}" in
                config)
                    COMPREPLY=($(compgen -W "-e --edit" -- ${cur})) ;;
                help)
                    COMPREPLY=($(compgen -W "$commands" -- "$cur" )) ;;
                log|report)
                    COMPREPLY=($(compgen -W "-f -t -p -T --from --to --project --tag" -- ${cur})) ;;
                remove)
                    COMPREPLY=($(compgen -W "-f --force" -- ${cur})) ;;
                start)
                    if [[ $COMP_CWORD -eq 2 ]]; then
                        projects="$(watson projects)"
                        COMPREPLY=($(compgen -W "$projects" -- ${cur}))
                    else
                        tags="$(watson tags | sed 's/.*/+\0/')"
                        COMPREPLY=($(compgen -W "$tags" -- ${cur}))
                    fi
                    ;;
            esac
            ;;
    esac

    return 0
}

complete -F _watson_complete watson
```

**Comment by willdurand** [comment]
:+1:

BTW, did you see this: http://click.pocoo.org/5/bashcomplete/?

**Comment by SpotlightKid** [comment]
Ah, ok, I was wondering how that pip completion code in my `~/.bashrc` works :)

Unfortunately, this is an all-nothing-solution, it seems. You can't customize it to support project and tag completion.

To implement frame ID completion, the following new watson command would be helpful (in the vein of `watson projects` and `watson tags`). I'm not sure, though, how helpful it would be to be presented with a list of opaque hex IDs when trying to find the frame to edit or remove.

```
@cli.command()
@click.pass_obj
def frames(watson):
    """
    Display the list of all frame IDs.

    \b
    Example:
    $ watson frames
    f1c4815
    9d1a989
    8801ec3
    [...]
    """
    for frame in watson.frames:
        click.echo(style('short_id', frame.id))
```

**Comment by willdurand** [comment]
> I'm not sure, though, how helpful it would be to be presented with a list of opaque hex IDs when trying to find the frame to edit or remove.

If it is not useful, then we can switch back to click's built-in completion feature, right?

**Comment by SpotlightKid** [comment]
No, since that doesn't give completion of projects and tags, AFAICS.

**Comment by willdurand** [comment]
You're right!

**Comment by k4nar** [comment]
@SpotlightKid : Did you had the chance to take a look at https://github.com/click-contrib/click-completion ?

**Comment by SpotlightKid** [comment]
No, I haven't. I wasn't aware of that project. How does it help completing Watson specific objects like project and tags?

Anyway, as you know, patches always welcome! :)
