### ISSUE TITLE
Set flake8 configuration to allow source code lines longer than 80 chars

### ISSUE THREAD

**Issue by timofurrer** [TailorDev/Watson#105]
I really like PEP8 but I would love to see some amendments. Especially the line-length rule. 
PEP8 really aims to improve the readability and maintainability of the code but often this line-length limit does quite the opposite.

See for example this failed build from PR #102 : https://travis-ci.org/TailorDev/Watson/jobs/112519286

Awesome project  :beers:

Great talk btw: https://youtu.be/wf-BqAjZb8M

**Comment by SpotlightKid** [comment]
> I really like PEP8 but I would love to see some adoptions.

I guess you mean amendments.

flake8 can be configured on a project basis, on a per-file basis (with special comments at the top of the file) and on a per-line/section basis. See the flake documentation for details.

Setting the convention for the maximum allowable line length is up to the project maintainers, though, I guess.

**Comment by SpotlightKid** [comment]
And, btw, IMHO that talk by Hettinger isn't really about whether PEP-8 or specific rules of it are good or bad. It's about looking at code with an eagle eye view for possible improvements and not missing the overall picture by concentrating only on coding style.

**Comment by timofurrer** [comment]
> I guess you mean amendments.

... *amendments* right - fixed it :beers: 

I know it can be configured, but still 80 characters .. you don't want to print it, right? I've seen several points where it doesn't help the readability and to insert the *disable-comment* on every line doesn't make sense either and for file and block scope much less.

I think just to increase the maximum to ... *90-100* would be sense.

As you've said ... it's up to the project maintainers - Just a little input ;)

> And, btw, IMHO that talk by Hettinger isn't really about whether PEP-8 or specific rules of it are good or bad. 

Exactly! Watch the first few minutes of the talk. Actually I had this part in mind: 
https://youtu.be/wf-BqAjZb8M?t=3m20s

**Comment by jmaupetit** [comment]
@SpotlightKid @k4nar do we need to increase the 80 chars limit? If yes, to which value?

**Comment by k4nar** [comment]
I don't feel that need, and I actually like this value because it means that I can easily split files in my editor.

So that would be a -1 for me, but if it's really preventing people from contributing to the project, we can change it.

**Comment by SpotlightKid** [comment]
At work we use 120 chars, which I personally find too much. I'm switching some personal projects to 100 chars, because with 80 you have to use tricks with parentheses to stay below the limit to often, which sometimes makes the code harder to read, rather than easier. But in this project there are only very few places where a longer line limit would have helped, AFAIR.

**Comment by jmaupetit** [comment]
My feeling is that 80 chars is fair enough. So I'll close this issue.
