### ISSUE TITLE
[Question] Is the 'frames' command necessary?

### ISSUE THREAD

**Issue by firecat53** [TailorDev/Watson#110]
Just wondering if there is a reason to keep the 'frames' command when the frame id is already given in the 'log' command? Especially since the 'log' command allows a from-to span applied to limit the results that are returned.

If there's not a specific reason to leave it as-is, I'd suggest either removing it or aliasing it to the 'log' command.

Thanks!
Scott

**Comment by SpotlightKid** [comment]
It is needed by the Bash completion.

**Comment by firecat53** [comment]
Ah, that answers my question, thanks!
