### ISSUE TITLE
Add a config for a "minimum" time interval (and/or rounding)

### ISSUE THREAD

**Issue by marcaube** [TailorDev/Watson#112]
**Feature request**

When I log my time, I always round to the nearest 15min increment. So my log looks something like this:

```
$ watson log
Monday 04 April 2016 (5h 15m 00s)
        e774dc5  10:00 to 11:45   1h 45m 00s  WEB-12472  [pr]
        752f528  12:45 to 13:00      15m 00s  WEB-12472  [pr]
        4fcedf9  13:00 to 13:45      45m 00s  WEB-13891  [crm, sync]
        84840f0  13:45 to 14:15      30m 00s  WEB-12472  [pr]
        04d318f  14:15 to 14:45      30m 00s  WEB-13814  [update]
        41307ff  14:45 to 15:45   1h 00m 00s  WEB-13872  [crm, rest]
        f683566  15:45 to 16:15      30m 00s  WEB-13638  [crm, rest]
```

Right now, I have to go back and edit all the frames one by one, which is a bit of a pain. So I'd like a config to define a minimum time interval, and another to choose a rounding strategy (floor, round, or ceil).

*With increments of 15 minutes*
- `floor(14h08) -> 14h`
- `round(14h08) -> 14h15`
- `ceil(14h08) -> 14h15`

*With increments of 30 minutes*
- `floor(14h08) -> 14h`
- `round(14h08) -> 14h`
- `ceil(14h08) -> 14h30`

Anyone else would benefit from this feature?

**Comment by jmaupetit** [comment]
Hi @marcaube ! Thank you for your feedback. In fact it's already a work in progress by @firecat53 in #109

**Comment by firecat53** [comment]
Still working on it! Just haven't had much time lately. The PR I submitted is functional and will give you a slightly different expanded report style + some rounding options.

Scott

**Comment by marcaube** [comment]
Oh sweet! Searched through the issues for this but missed the PR. It seems that the rounding is done on the total time rather than the projects time though, am I right ?

**Comment by firecat53** [comment]
The total hours for each tag are summed for the calendar day and then each
tag total is rounded up to x minutes. The total of those rounded sums is
presented as the project total for the time period. I'm explaining it
horribly... The given examples should make it more clear I hope. (Or the
source)

Scott

**Comment by marcaube** [comment]
Hum, then I might just be using it wrong. If I used tags (instead of projects) for my Jira tasks, then I would get a per-task total. I'll have to play with it and change my workflow a bit.

@jmaupetit and @firecat53, thanks for the answers, I'm closing here since it's a duplicate of the PR #109
