### ISSUE TITLE
Make backup before writing to prevent possible loss of frames file

### ISSUE THREAD

**Issue by SpotlightKid** [TailorDev/Watson#118]
During development I accidentally introduced an error in `frames.Frames.dump()`, which wasn't caught in `watson.Watson.save()` and resulted in my frames file being wiped, i.e. ending up as a zero-length file (I had a backup of course).

I think we should do the following:

* Write the new frames file to a different file first and move it to the destination only if the write was successful.
* Keep the previous file as a backup.

We could move the existing file out of the way first, but then we would need to revert this, if the write fails.

**Comment by k4nar** [comment]
Yes, it seems like a very good idea.
