### ISSUE TITLE
Batch import (via CSV)?

### ISSUE THREAD

**Issue by minthemiddle** [TailorDev/Watson#137]
I would like to migrate to Watson but have an open project that I would like to migrate as well. I have about 40 frames (start, end, project, tags). Right now the only way to get data into Watson would be to start and stop 40 times and edit the frames one by one or figure out the way Watson sets IDs and times and create a custom dictionary.

Do you have any work around or import script or is this something that is missing?

**Comment by SpotlightKid** [comment]
Do you have a sample of the input data format?

**Comment by minthemiddle** [comment]
Sure. Here are the first two lines of the CSV (sorry, German dates dd.mm.YY, last column is auto calculated from start to end, but either could be deleted if neccessary)

```
date,note,tag,project,start,end, hh:mm
29.09.16,Work on hero image,Code; Design,1601-localhon,17:30:00,17:00:00,00:30:00
```

**Comment by k4nar** [comment]
If you are familiar with Python it shouldn't be an issue :) . For now we don't have an official doc on how to play with Watson Python API, but basically you would need to:

- Instantiate a [Frames](https://github.com/TailorDev/Watson/blob/master/watson/frames.py#L71) object
- [Add](https://github.com/TailorDev/Watson/blob/master/watson/frames.py#L136-L137) each of your frame from your CSV (1 line = one frame) 
- [Write](https://github.com/TailorDev/Watson/blob/master/watson/watson.py#L154-L155) the frames

It's a bit messy and I'm sure it could be improved in many ways, but it should work :) .

**Comment by SpotlightKid** [comment]
Here's a quick-and dirty script, that should do the trick. Note that it will happily add the same data twice if you run it more than once:

```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#  watson_import_csv.py
#
"""Short one line description."""

import argparse
import csv
import logging
import sys
import os

from datetime import datetime

from watson import Watson


FIELDS = "date,note,tag,project,start,end,duration".split(",")
DATE_FORMAT = '%d.%m.%y'
TIME_FORMAT = '%H:%M:%S'
log = logging.getLogger("import_csv")


def import_csv(infile):
    watson = Watson(config_dir=os.environ.get('WATSON_DIR'))
    parser = csv.DictReader(infile, delimiter=",")

    for row in parser:
        log.debug("INPUT row: %r", row)
        try:
            date = datetime.strptime(row['date'], DATE_FORMAT).date()
            start = datetime.strptime(row['start'], TIME_FORMAT).time()
            stop = datetime.strptime(row['end'], TIME_FORMAT).time()
            start = datetime.combine(date, start)
            stop = datetime.combine(date, stop)
            tags = [tag.strip() for tag in row['tag'].split(';') if tag.strip()]
            now = datetime.utcnow()
            message = row['note'].strip() or None
            log.debug("Adding frame: project=%s, start=%s, stop=%s, tags=%s, ",
                      "updated_at=%s, message=%s", row['project'], start, stop,
                      tags, now, message)
        except Exception as exc:
            log.error("Could not parse row data %r: %s", row, exc)
        else:
            watson.frames.add(row['project'], start, stop, tags, now, message)

    watson.save()


def main(args=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('-v', '--verbose', action="store_true",
        help="Be verbose")
    ap.add_argument('infile', type=argparse.FileType('r'), help="Be verbose")

    args = ap.parse_args(args if args is not None else sys.argv[1:])

    logging.basicConfig(format="%(name)s: %(levelname)s - %(message)s",
        level=logging.DEBUG if args.verbose else logging.INFO)

    import_csv(args.infile)

    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]) or 0)
```

**Comment by SpotlightKid** [comment]
Please note that my example is script is supposed to work with #119 applied.

**Comment by minthemiddle** [comment]
Excellent solution, thanks a lot @SpotlightKid. Can easily get adopted to special needs.
