### ISSUE TITLE
Should the source distribution contain the generated HTML documentation?

### ISSUE THREAD

**Issue by SpotlightKid** [TailorDev/Watson#142]
At the moment, it doesn't. We would need to adapt the `MANIFEST.in` file to do it.

To generate the HTML documentation you need to install the dev requirements. On the other hand, the documentation can always be viewed online.

Opinions?

**Comment by jmaupetit** [comment]
When going off-line, Markdown sources are still available. So, I would say no.

**Comment by willdurand** [comment]
What about having a command for serving the documentation (offline)?

**Comment by SpotlightKid** [comment]
```
make docs
cd site
$BROWSER http://localhost:8000/ &
python -m http.server
```

**Comment by SpotlightKid** [comment]
But the point is that making the docs requires installing a lot of additional stuff, which could be a PITA when you don't have a dedicated virtualenv for Watson, which you probably don't, if you just want to use Watson.

**Comment by k4nar** [comment]
Okay for including the docs, but who's gonna go in the installed sources to read it? :)

Anyway, that would be :+1: for me if it doesn't add much space to the package.

**Comment by SpotlightKid** [comment]
Unfortunately, including the HTML docs blows up the sdist from 8 Mb to 18 Mb. About 95% of the size are the images in `doc/img`, which then get included again under `site/img`. And 90% of the size of the images is the animated gif of the cat. :)

**Comment by SpotlightKid** [comment]
BTW, the wheel is only about 20 kB :) which should make downloading and installing Watson much faster for most users.

**Comment by willdurand** [comment]
Let's not add the doc then. It is fine online, and we could have a command to `open <doc url>`.

**Comment by davidag** [comment]
Should this issue be closed? It looks like a decision was made :)
