### ISSUE TITLE
How to get clean timesheet with frames with multiple tags?

### ISSUE THREAD

**Issue by minthemiddle** [TailorDev/Watson#144]
I usually attach more than one tag to a frame, such as `watson start projectx +design +navigation`.  Let's say I track 1h with this command. When I do a `watson report --project projectx` I would get a total of 2h because it tracks both tags separately.

How can I avoid this without migrating to a single tag only workflow?

**Comment by k4nar** [comment]
You wouldn't get a total of 2h. You would get a total of 1h, and then the time that you spent on each tag individually. It makes sense because you could also have spent some time on `projectx +design +tests` for instance :) .

**Comment by minthemiddle** [comment]
That is actually what I expected. Turns out that I had a non-stopped watson frame that skewed my stats.
