### ISSUE TITLE
Total time not shown when doing `watson report` with default options

### ISSUE THREAD

**Issue by canro91** [TailorDev/Watson#146]
When doing `watson report`, with default options, the total time is not shown. Even tough, the documentation for `report` command shows it in a example output.

**Comment by SpotlightKid** [comment]
The overall total time is only shown if the report includes sub-reports for _several_ projects. If there's only one project shown, the overall total time is equal to the total time of the project.

**Comment by SpotlightKid** [comment]
Closing this. Works as designed.
