### ISSUE TITLE
Add a new `spent` command ?

### ISSUE THREAD

**Issue by shulard** [TailorDev/Watson#147]
Hello,

I think adding a `spent` command which will generate directly a new frame can be a nice addition... Personnaly I'm not sure that I'll think to run the `start` before effectively starting to work on something...

I know it'll require a bit of discipline but if I forgot to start, is there actually a way to create a frame without start / stop / edit ?

Thanks.

**Comment by SpotlightKid** [comment]
You can already edit the running frame, directly after the start command, but currently there is no command line interface to directly create a finished frame or to start a frame with a starting time other than now.

**Comment by SpotlightKid** [comment]
Specifying a starting time other than now is discussed in #75.

**Comment by shulard** [comment]
Hello,

The start option seems interesting but what I describe here is about an already finished time frame that you want to log. For me using the `start` start command with option is a bit complicated because you need to `start` then `stop`...

Maybe when the #75 will be done, the `spent` command can be introduced like a wrapper to `start` then `stop` call ?

Also the `spent` command can have the advantage to allow adding a past frame in the history...

**Comment by SpotlightKid** [comment]
Yes, I realize, that what you are proposing is not the same as an option to the start command for setting the start time. Otherwise I would have closed this issue as a duplicate ;).

I like the general idea, but I'm not sure about the name. Any other suggestions than `spent`?

**Comment by jmaupetit** [comment]
What about `add`?

**Comment by shulard** [comment]
Indeed, seems a simpler name 👍. Finally this new command will just be able to add a new frame...

**Comment by b3niup** [comment]
+1 for this idea :)

**Comment by SpotlightKid** [comment]
@caillou: Please see issue #75.

**Comment by caillou** [comment]
@SpotlightKid I did. It is a 2 year old issue that does not seem to go anywhere, hence the question.

**Comment by SpotlightKid** [comment]
Still, it is the issue about the feature you are alluding to with your first example.

In you second example, the duration fits more with what the OP suggested in this issue. So we have two feature requests, hence two tickets :)

As always, PRs are welcome. To add options to commands, you need to edit `cli.py`. Eg. for the `start` command here:

https://github.com/TailorDev/Watson/blob/master/watson/cli.py#L116

But to support setting the start time, the signature of `watson.Watson.start()` would probably have to be changed as well:

https://github.com/TailorDev/Watson/blob/master/watson/watson.py#L242

The line were a new frame is started is here:

https://github.com/TailorDev/Watson/blob/master/watson/watson.py#L257

This triggers the setter method of the `Watson.current` property. You'd need to pass a value for `start` here,. There's no way to pass the `stop` time directly yet.

**Comment by willdurand** [comment]
I can probably give it a try this week.

**Comment by mrietveld** [comment]
One of the (zsh) alias that I end up using a lot is this: 
```
wstd () {
	$watson start "$@"
	$watson edit `watson frames | tail -1`
	$watson edit
}
```
This allows me to 
1. Start a new frame (and stop the current one: I have `stop_on_start = true`)
2. Directly edit the stopped frame in order to set the time it stopped
3. Directly edit the new frame to edit the time the new frame started

I use this whenever I've switched tasks but forgotten to tell Watson that I did so. Sometimes, I even use this alias 3 times in a row (to add the last 3 or 4 tasks/frames). 

`watson add` is basically this functionality! It would be great to get this.

**Comment by jmaupetit** [comment]
Fortunately, there is a new command for that: `watson add` (unreleased yet). See #202. Hat tip to @braincow & @BuddhaOhneHals :pray: 

I'll close this issue. Feel free to pursue this discussion if this new command is not exactly what you wished for.
