### ISSUE TITLE
Which python versions does watson support?

### ISSUE THREAD

**Issue by crocket** [TailorDev/Watson#149]
I want to package watson for gentoo linux.
Which python versions does it support?

**Comment by crocket** [comment]
Never mind. I found supported versions from `setup.py`.

**Comment by SpotlightKid** [comment]
All versions tested via tox as configured in the `tox.ini` file. Namely py27, py33, py34, py35. Python 3.6 too, but it's not automatically tested yet. I will it add later.

**Comment by crocket** [comment]
Thanks.
