### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by willdurand** [TailorDev/Watson#164]
The project requirements should be updated.

**Comment by SpotlightKid** [comment]
What's this about specifically? `setup.py` / `requirements.txt` or `tox.ini`? Or the docs? Has been addressed by #175 and #180?

**Comment by davidag** [comment]
Dev requirements were also updated in #304.

**Comment by jmaupetit** [comment]
I'm not sure how to deal with this issue as the title/description may never get fulfilled. I'll close this and we will re-open less vague issues on a per-dependency basis.
