### ISSUE TITLE
Default EDITOR is not honored

### ISSUE THREAD

**Issue by lucasefe** [TailorDev/Watson#168]
When I `watson config -e` to edit my condifguration, `nano` opens, instead of my default 
```
~ env | grep EDITOR
EDITOR=vim
```

I noticed `watson` uses `click`, and the problem is probably related to it, and not to `watson` itself but since my python knowledge is minimal, I'm reaching out to you to check whether this is something common/known. 

Thanks in advance.

**Comment by SpotlightKid** [comment]
The value of the environment variable `VISUAL` takes precedence over `EDITOR`.

See here: https://github.com/pallets/click/blob/master/click/_termui_impl.py#L384

You probably have set `VISUAL` to `nano`.

**Comment by lucasefe** [comment]
@SpotlightKid you know your env variables. Thank you so much. That was it.
