### ISSUE TITLE
Where is data stored?

### ISSUE THREAD

**Issue by kevinhowbrook** [TailorDev/Watson#170]
Hi, thanks for this tool. It's really useful. I wanted to make a front end/csv writer for this but not sure where data is stored, or even if data is writing to a file. Are reports generated from a master file being written to?

**Comment by willdurand** [comment]
Hi!

Data is stored in a plain old JSON file, in the `watson` **app directory** usually. See: http://click.pocoo.org/5/api/#click.get_app_dir.

Note that we have app.crick.io if you want a web dashboard.

**Comment by jmaupetit** [comment]
Thanks for your kind words Kevin. I am closing this issue since we answered your question.

**Comment by sundarv85** [comment]
Would be good if we could have an option to switch the location. We could then decide to save it in a separate folder.

**Comment by willdurand** [comment]
@sundarv85 if you're using a unix system, then you can use the `XDG_CONFIG_HOME` env var.
