### ISSUE TITLE
Watson installed through pip but getting command not found error

### ISSUE THREAD

**Issue by paanvaannd** [TailorDev/Watson#174]
System: Ubuntu 17.10
pip version: 9.0.1 (python 2.7)

The output of `pip list | grep td-watson` shows that `td-watson` is installed yet calling the `watson` command does nothing: ZSH reports that the command is not found.

Any help on how to proceed would be appreciated!

**Comment by jmaupetit** [comment]
Hi @paanvaannd! Can you type the following command in a terminal and copy/paste the output to get more info about where `td-watson` was installed:

```bash
$ pip show td-watson
```

**Comment by paanvaannd** [comment]
Sure!

Location: `~/.local/lib/python2.7/site-packages`

**Comment by jmaupetit** [comment]
Ok, so I think `watson` is installed in `/home/user/.local/bin`. You need to add this directory to your path by adding the following line to your `.bashrc`:

```bash
# $HOME/.bashrc
export PATH="$HOME/.local/bin:$PATH"
```

And then source it:

```bash
$ source $HOME/.bashrc
```

… or launch a new terminal. And the `watson` command will be available.

**Comment by paanvaannd** [comment]
Well that was a rookie mistake; can't believe I didn't check that first!

Thanks for the help, and I look forward to using Watson :+)

**Comment by jmaupetit** [comment]
Sure! @mb941 or @paanvaannd are you motivated to make a PR for this?

**Comment by paanvaannd** [comment]
I would probably not have much to contribute to the README documentation other than a copy-paste of your response, @jmaupetit. If that's all that is really required (besides maybe re-wording here and there), then I could do so tomorrow!

However, I would like to be thorough as well. You mentioned that `watson` installs to `/home/user/.local/bin` which was the case for me, but might `pip` be configured to install packages elsewhere? If so, it would be good to point out users to echo that `pip` package installation path and be sure to add that directory to the `$PATH` variable.

**Comment by jmaupetit** [comment]
:thinking: After checking the docs, I missed that we already have documented the single-user installation procedure (see: https://tailordev.github.io/Watson/#single-user-installation). Do you think it's required to also add it to the README? IMO it's not.

**Comment by paanvaannd** [comment]
@jmaupetit Yeah perhaps it's not necessary then.

In fact, if anything, I would recommend taking out all install instructions from the README and simply directing them through a link to the documentation to prevent any confusion. Or just leave it as is. What do you think?

**Comment by jmaupetit** [comment]
I like the idea to have a quickstart in the README and a more detailed documentation elsewhere. But, I have no strong feelings about this. @SpotlightKid @k4nar @willdurand WDYT?
