### ISSUE TITLE
Support for utf-8

### ISSUE THREAD

**Issue by h4llow3En** [TailorDev/Watson#184]
Characters like ö, ä, etc. are not supported and throws an
`UnicodeEncodeError: 'ascii' codec can't encode character`

This ist because of the use of Python 2.7

**Comment by SpotlightKid** [comment]
Can you please post the command that you ran and complete error message with the full traceback?

**Comment by xispa** [comment]
```
$ watson start revisió projecte foo +memo
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 7, in <module>
    from watson.__main__ import cli
  File "/usr/local/lib/python2.7/dist-packages/watson/__main__.py", line 6, in <module>
    cli.cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/watson/cli.py", line 154, in start
    _start(watson, project, tags)
  File "/usr/local/lib/python2.7/dist-packages/watson/cli.py", line 110, in _start
    style('time', "{:HH:mm}".format(current['start']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 11: ordinal not in range(128)
```

**Comment by jmaupetit** [comment]
Hi @xispa! Thanks for the report. I think this command cannot work properly (but I'm not sure its related to the bug you have reported). Can you rather run the following command?

```
$ watson start "revisió projecte foo" +memo
```

**Comment by jmaupetit** [comment]
And paste the output of the `locale` command, _e.g._:

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

Are you running MacOSX or Linux?

**Comment by jmaupetit** [comment]
> It might happen because the watson/__main__.py has no utf-8 annotation?

Have you tested to add it?

> I think if you would use emoji this would happen as well...

:+1: and this is a major issue, i do agree :laughing:

**Comment by h4llow3En** [comment]
One solution would be to convert this project to Python 3..

**Comment by jmaupetit** [comment]
This project is already python 3 ready! I use it on a daily basis. If you can, yes I strongly invite you to run it with python 3.

```bash
$ (sudo) pip uninstall td-watson
$ (sudo) pip3 install td-watson
```

**Comment by h4llow3En** [comment]
But the homebrew version somehow seems to be using python2.

**Comment by jmaupetit** [comment]
> I don't think adding # -*- coding: utf-8 -*- at the top of the file will help, cause it mainly refers to the encoding for the file itself.

@xispa totally true, my remark was stupid...

**Comment by jmaupetit** [comment]
> But the homebrew version somehow seems to be using python2.

True. I have to confess that since I've switched back to GNU/Linux, I haven't put efforts in making it available for python3. But, if you have a working python 3 distro on your Mac, try uninstall the homebrew release and install it with pip(3).

**Comment by k4nar** [comment]
Actually I think all it has already been fixed in https://github.com/TailorDev/Watson/pull/212, but isn't released yet.

So maybe it's time for a new release @jmaupetit ?

**Comment by jmaupetit** [comment]
Yup.

**Comment by ThomasWaldmann** [comment]
non-ascii project names work for me (python 3.5.3) for current git master.

**Comment by davidag** [comment]
This one also seems to closeable :+1:

**Comment by jmaupetit** [comment]
Thanks for your careful attention to this project's maintenance @davidag 🙏

**Comment by davidag** [comment]
@jmaupetit I'm glad I can help! It's also an effort to find the best next way to contribute to the project :relaxed:
