### ISSUE TITLE
Problem with the `sync` command.

### ISSUE THREAD

**Issue by shulard** [TailorDev/Watson#186]
Hello,

I've just created an account on Crick to synchronize my frames on the web. After configuring my watson backend url and token I get an error when running `watson sync`:

```
Error: Unable to reach the server.
```

I read part of the Watson source code the check how the API requests are made and if I call the API directly with cURL, I get a response...

```
curl -H "Content-Type: application/json" -H "Authorization: Token mytokenhere" -vvv https://api.crick.io/watson/projects
```

Give me : `{"projects":[]}`.

Is there a way to check what kind of error appear here ?

**Comment by willdurand** [comment]
Do you see anything else by chance? Also, wasn't it a temporary network issue?

**Comment by shulard** [comment]
Hello,

Actually, it doesn't seems to be a network issue because I can interact with the API by hand. Is there another way than tcpdump to analyse what watson do at this particular moment ?

I don't see anything else at the moment but I'll continue to check.

**Comment by shulard** [comment]
I also use Little Snitch on my mac and when I check the connection log, he tells me that they are successful.

Does watson do something different than a GET request on `https://api.crick.io/watson/projects` with the valid headers ?

**Comment by willdurand** [comment]
I don't know the internals of Watson well, but I only see the error message 3 times in the codebase. It looks like the HTTP lib raises a connectivity exception, and that's weird. HTTP errors should be caught by a different exception (like missing header, wrong method, wrong payload)

**Comment by shulard** [comment]
Yeah, so this error seems to be related to my current setup 😄.
I'll check inside my local installation (from homebrew formula) if I can find more details...

**Comment by shulard** [comment]
Ok so I've made other tests in my local python code.

The error is triggered inside the `pull` method and it's a `requests.ConnectionError` so it's triggered before the response was computed...

I've dumped to exception details :

`request`: 

```{'body': None, 'url': 'https://api.crick.io/watson/frames?last_sync=1970-01-01T00%3A00%3A00%2B00%3A00', 'hooks': {'response': []}, 'headers': {'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.2', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Authorization': 'Token mytokenhere'}, '_body_position': None, '_cookies': <RequestsCookieJar[]>, 'method': 'GET'}```

`response`: `None`

With that I don't see any problems... But I don't know enough python to go further... Is this kind of message helping to identify the problem ?

**Comment by willdurand** [comment]
I dont see anything in the logs 🤔

@jmaupetit is that ok to receive a `None` response?

**Comment by jmaupetit** [comment]
Nope it's not.

@shulard can you execute this snippet in your python console (using the same python distribution that  Watson is installed in)?

```python
import requests

headers = {
    'Accept-Encoding': 'gzip, deflate',
    'Accept': '*/*', 
    'User-Agent': 'python-requests/2.18.2',
    'Connection': 'keep-alive', 
    'Content-Type': 'application/json', 
    'Authorization': 'Token yourtokenhere',  # add your token here
}

dest = 'https://api.crick.io/watson/frames?last_sync=1970-01-01T00%3A00%3A00%2B00%3A00'

response = requests.get(dest, headers=headers)

assert response.status_code == 200

# display json formatted response (if any)
response.json()
```

**Comment by shulard** [comment]
Hello @jmaupetit, 

I've executed the given snippet in my python console and got the following error on the `requests.get` call :

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/watson/1.5.2_1/libexec/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.crick.io', port=443): Max retries exceeded with url: /watson/frames?last_sync=1970-01-01T00%3A00%3A00%2B00%3A00 (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

My Watson binary is executed with Python 2.7.10.
```

**Comment by willdurand** [comment]
looks like a SSL/TLS issue

**Comment by jmaupetit** [comment]
I think it might be related to OpenSSL. You can check used release via:

```bash
# Using Watson's python
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
```

@shulard how did you install OpenSSL on your system?

**Comment by shulard** [comment]
It seems that I have an old version installed on my system and which is used by Watson...

```
$ libexec/bin/python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 0.9.8zh 14 Jan 2016
```

OpenSSL is installed using Homebrew on my system but it seems that this is not the version used by the Python binary bundled with Watson...

When I check the openssl version directly :

```
$ openssl version
OpenSSL 1.0.2n  7 Dec 2017
```

When I check with the Python 2.7 and Python 3 binaries installed using Homebrew, I got the right version :

```
$ python2 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2n  7 Dec 2017

$ python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2n  7 Dec 2017
```

I tried to uninstall / reinstall Watson using Homebrew but the problem stay the same...

**Comment by jmaupetit** [comment]
`libexec/bin/python` is not the same python distribution as the one targeted by `python2`?

**Comment by shulard** [comment]
Nope, maybe it's a homebrew specific issue. There is a python binary (not a symlink) inside the `libexec/bin` folder in my watson install dir.

I tried to update create a symlink to tell watson to use the python2 (with valid SSL) : 

```bash
mv python python.installed
ln -s /usr/local/bin/python2 python
```

Then I got this error&nbsp;:

```bash
$ watson sync
Traceback (most recent call last):
  File "/usr/local/bin/watson", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'td-watson==1.5.2' distribution was not found and is required by the application
```

I'm not familiar enough with Python and Homebrew formula handling to know how this python binary has arrived here...

I saw that in the Formula, there is a line about python dependency :

```ruby
depends_on "python" if MacOS.version <= :snow_leopard
```

Maybe the MacOS bundled python is valid after Snow Leopard ?

**Comment by jmaupetit** [comment]
Let's try to uninstall homebrew release and use the python way to re-install Watson:

```
$ brew uninstall watson
$ sudo -H pip3 install td-watson
```

**Comment by shulard** [comment]
If I uninstall from homebrew and install with pip it works. We are now sure that it's a Homebrew related issue.

Sorry if I'm the first one to encounter that error 😄, maybe it's related to my current setup...

I'll dig a little deeper in Homebrew virtualenv helpers because python must be installed from that functions.

**Comment by jmaupetit** [comment]
Don't be sorry, Watson must be open to non-pythonista users 😉 

I'll close this for now.
