### ISSUE TITLE
Warn on new projects and tags

### ISSUE THREAD

**Issue by MinchinWeb** [TailorDev/Watson#191]
As I keep using Watson, I find that I use maybe three dozen different projects and tags, and that new projects are fairly rares. I imagine most people work similarly.

So most "new" projects are just mis-spellings (or capitalization changes) of existing projects.

So I think it would be nice for Watson to warn you on creating a "new" project, and ask you if you want to correct it. Is there support to implementing such a feature?

**Comment by k4nar** [comment]
Maybe we could try to be clever and check if the given names is close from the name of an existing project ? However this could be annoying, as for example `foo-q1` & 'foo-q2' will have a very short distance, but the later is probably not a typo.

Also if we ask for a confirmation it might be annoying for wrapper around `watson start`.

Anyway, this is a good idea, I wonder if we can find a good way to handle it.

**Comment by willblatt** [comment]
I run into this a lot; less so on linux due to the bash autocomplete abilities.

Perhaps the default behavior could be something like:
```watson start <project> --warn-new-project``` 
and for those that prefer to have that flag on by default, the config file could contain
```ini
[options]
warn-new-project = true

**Comment by smaslennikov** [comment]
Can confirm, would be extremely useful.

**Comment by braincow** [comment]
There we go. Initial implementation in the pull request #218

**Comment by davidag** [comment]
This issue was fixed after merging #275 :+1:

**Comment by jmaupetit** [comment]
Yup, but unfortunately it is not documented as configurable. I forgot this in my review :sweat:
