### ISSUE TITLE
Logs disappeared after reboot, sync not working

### ISSUE THREAD

**Issue by Ganitzsh** [TailorDev/Watson#193]
Hi there,

Just rebooted my MacBook and all the logs from my watson just disappeared. I tried to run `watson sync` but I'm getting the following error: `watson.watson.ConfigurationError: You must specify a remote URL (backend.url) and a token (backend.token) using the config command` which is pretty obvious but I have no idea of what token it's waiting for.

I checked the documentation and it appears in the configuration section but it does not say where to get it and why.

Any chance someone can help?

Thanks!

**Comment by willdurand** [comment]
Hi, you should get an account on app.crick.io if you want to use `watson sync`. Sorry for that..

**Comment by Ganitzsh** [comment]
Perfect, thanks!
