### ISSUE TITLE
How to check if Watson is running?

### ISSUE THREAD

**Issue by ademcan** [TailorDev/Watson#195]
Hi and thanks for the amazing tool.
I often had the issues that I forgot to stop Watson and then end up with incorrect times.
I think that a really nice option would be to have a small menubar app that informs us if we have a Watson session running or not (i.e green/red button).
Is there a way to check if Watson is running (based on process information for example)? I would be happy to see what I can do as a "GUI" for MacOS.

**Comment by willdurand** [comment]
We have integrations for various tools if I remember correctly. For instance, I use zsh + [pure](https://github.com/sindresorhus/pure) and I tweaked it a bit: https://github.com/willdurand/dotfiles/blob/0f1b542f70de98b0496989569b524eed6784f5d2/zsh/pure/pure.zsh#L133-L139

TailorDev blogged about some tools too: https://tailordev.fr/blog/2016/03/31/watson-community-tools/

**Comment by willdurand** [comment]
To better answer your question, we check if the `state` file exists and is not `{}` to know when watson is started.

**Comment by ademcan** [comment]
Oh cool, thanks a lot @willdurand. I missed this blogpost...
I am already in love with watson-tray (https://github.com/jmaupetit/watson-tray) 👍 
Thanks again for the quick reply.

**Comment by jmaupetit** [comment]
Hey @ademcan it's probably buggy and out-of-date! AFAIK I was the only one to use it :grin:

**Comment by ademcan** [comment]
Not anymore😄 It is exactly what I was looking for!
