### ISSUE TITLE
watson log does not show frame id

### ISSUE THREAD

**Issue by Hacktivista** [TailorDev/Watson#196]
watson log suddenly stopped showing the frame id on my machine

![no-frame-id](https://user-images.githubusercontent.com/5282749/37209786-39443380-2385-11e8-95c8-8c390402a68e.png)

Any help?

**Comment by jmaupetit** [comment]
Can you try again with a darker terminal background?

**Comment by Hacktivista** [comment]
Ha! You right! haha, any way to change colors?

**Comment by jmaupetit** [comment]
Not yet. There is an open issue for that (see #94). At the time of writing, you'll find those settings here: https://github.com/TailorDev/Watson/blob/master/watson/utils.py#L32

Feel free to propose a PR to solve this! :heart:
