### ISSUE TITLE
Document installation with homebrew

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#2]
It might be nice to add a homebrew formulae to distribute watson for Mac users.

Must read [this](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md) first.

**Comment by jmaupetit** [comment]
We need to tag a release first.

**Comment by jmaupetit** [comment]
As mentioned in [homebrew docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md#introduction):

> Homebrew generally won't accept libraries that can be installed correctly with `pip install foo`.

**Comment by jmaupetit** [comment]
Just submitted a [PR for homebrew integration](https://github.com/Homebrew/homebrew/pull/49067).

**Comment by jmaupetit** [comment]
This PR has been merged. You can now `brew update && brew install watson` \o/

**Comment by jmaupetit** [comment]
Reopen this issue while it's not documented.

**Comment by SpotlightKid** [comment]
PR #121, which documents this, was merged.
