### ISSUE TITLE
documentation: explaining 'frame' and config

### ISSUE THREAD

**Issue by braingineer** [TailorDev/Watson#20]
Hi!

Great project so far =).

A couple things, though.  Currently, there is nothing in the readme explaining what a frame is (I'm guessing it's a logging instance--aka one start and stop).  Also, you don't say anywhere what the config options are, or what "crick" is.  

Best,
Brian

**Comment by braingineer** [comment]
Also, typing `watson sync --help` references the [Django Crick project](https://bitbucket.org/tailordev/django-crick) but the project is private and I cannot view it.

**Comment by willdurand** [comment]
@braingineer yeah, sorry for that. We've open sourced an internal tool actually, and while extracting it from our stack, we did not remove all references to our internal dependencies.

**Comment by willdurand** [comment]
To answer your question, _crick_ is our internal time tracker API, now part of the [artich.io](https://artich.io/) platform. It is an alternative backend as one of the aims of Watson is to be able to talk to different backends.
