### ISSUE TITLE
--format option doesn't exits

### ISSUE THREAD

**Issue by Armageddonas** [TailorDev/Watson#204]
Command `watson report --format json` as reffered in the [commands page](https://tailordev.github.io/Watson/user-guide/commands/) does not work. Although `watson report --json` and `watson report -j` can be used as an alternative. So the fault is propably in the documentation.

**Comment by jmaupetit** [comment]
Yup you're right, thanks for the report. We'll need to fix this and/or update the documentation.

**Comment by Armageddonas** [comment]
Happy to help

**Comment by davidag** [comment]
This seems to be fixed already. If so, maybe the issue could be closed?

**Comment by k4nar** [comment]
Indeed, thanks @davidag!
