### ISSUE TITLE
Cut a new release because 1.5.2 doesn't build.

### ISSUE THREAD

**Issue by crocket** [TailorDev/Watson#206]
When I try to build 1.5.2, I get the following error message.

> error in td-watson setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed

This issue was fixed after the release of 1.5.2

**Comment by jmaupetit** [comment]
Yup you're right, thanks for the report. Time is short for open source side projects these days...

**Comment by willdurand** [comment]
I am on it, see: https://github.com/TailorDev/Watson/releases/tag/1.6.0

**Comment by willdurand** [comment]
Ok this should be all good now, Homebrew should also get an update soon: https://github.com/Homebrew/homebrew-core/pull/26973.
