### ISSUE TITLE
Watson report day by day

### ISSUE THREAD

**Issue by elbryan** [TailorDev/Watson#216]
Hello! Is it possible to make Watson report logged time day by day?

I am essentially trying to replicate what depicted by the image in the [official page](http://tailordev.github.io/Watson/) but instead I get a "group by" week with all the projects aggregated. Instead I am interested in the day-by-day report as displayed in the picture in the page linked above.

**Comment by elbryan** [comment]
@mrietveld thank you for answering. `watson log` doesn't aggregate the various frames, does it?

**Comment by jmaupetit** [comment]
A daily report from a time span would be a great feature that has not been implemented yet. Submit a new PR!

**Comment by brandomr** [comment]
Is this still an open feature request? I'm interested in this as well. Maybe it's something I could help with.

**Comment by jmaupetit** [comment]
Yes! Thanks for your help :pray:

**Comment by brandomr** [comment]
@jmaupetit @elbryan See PR #231

**Comment by jmaupetit** [comment]
We'll take a look on this @brandomr. Thanks!

**Comment by KennethNielsen** [comment]
This issue seems to be closed with #231 right?

**Comment by jmaupetit** [comment]
Well spotted @KennethNielsen :pray:
