### ISSUE TITLE
Install on Ubuntu 16.04

### ISSUE THREAD

**Issue by lesar** [TailorDev/Watson#228]
Can some one help to the right command to install watson on ubuntu 16.04?  
Have I to use `sudo` or `sudo -H` or `not sudo` to globally install watson?
  
I have python 2,7 and 3,5.  

if I prompt python -V it give me 2.7.  

which version is better to use for watson?  
How to use pip to right install watson on Ubunti 16.04?  

Best regards,
Leonardo

**Comment by jmaupetit** [comment]
Hi @lesar ! In your case, I think the best way to install Watson globally is to use python3 and `sudo`:

```bash
$ sudo -H pip3 install td-watson
```

**Comment by lesar** [comment]
Yea, I like it. work very well tank you. :-)
