### ISSUE TITLE
Stop frame at given time

### ISSUE THREAD

**Issue by MaxG87** [TailorDev/Watson#233]
Hi and thank you for that awesome program.

Sometimes I want to log time for several frames already finished. The typical use case would be that you have a short conversation/ad-hoc meeting with colleague A on Project 1, then you switch on Project 2 and then you visit colleague B to talk about Project 1 again. One cannot log times for that instantly but has a rough idea about the times. This kind of use case is not too seldom, at least for me.

Currently, this kind of use case requires extensive use of `watson edit`, which is quite burdensome. It would be great to have a `--at` option, so that one can issue

    watson start Meetings +Project_1
    #Go chatting to several colleagues
    watson stop --at 13:37

This request is closely related to https://github.com/TailorDev/Watson/issues/75.

I will request corresponding flags on `watson start` in a seperate PR.

**Comment by loonies** [comment]
What about `watson stop --at 12:34` to match `watson start --at` ?

**Comment by acidjunk** [comment]
Very nice feature (handy for start, stop and restart)

**Comment by varac** [comment]
Isn't this already implemented by aa901567c5aa6129ff6dae799eddbfb0be06cb65 ?

**Comment by k4nar** [comment]
Indeed :+1: .
