### ISSUE TITLE
Start new frame seamlessly to old frame

### ISSUE THREAD

**Issue by MaxG87** [TailorDev/Watson#234]
Sometimes I want to log time for several frames already finished. An exemplaric use case is given in 
https://github.com/TailorDev/Watson/issues/233.

It would be great if there was a way to start a new frame seamlessly to the old one. Then, at the end of several short meetings, one could issue

    watson start Project_1 +Meetings
    #Go chatting to several colleagues
    watson stop --at 13:37
    watson start Project_2 +Meetings --seamless
    watson stop --at 13:51

This PR is closely related to https://github.com/TailorDev/Watson/issues/75, https://github.com/TailorDev/Watson/issues/233 and https://github.com/TailorDev/Watson/issues/28.

Thank you very much.

**Comment by MaxG87** [comment]
I have nothing prepared, but I will give it a try.

**Comment by MaxG87** [comment]
As you can see in https://github.com/TailorDev/Watson/pull/235, I managed to dive into the codebase. It will take me a week or two. I hope that this is ok.

**Comment by jmaupetit** [comment]
Of course it's ok! You owe us nothing. Take your time.

**Comment by MaxG87** [comment]
Shouldn't this issue be closed now?
