### ISSUE TITLE
Fish Shell completions

### ISSUE THREAD

**Issue by martinklepsch** [TailorDev/Watson#242]
[Fish](https://fishshell.com) is a very nice shell and it would be nice if this project would ship completions for Fish as well. I unfortunately have never written any completions for Fish but the folks maintaining it are very nice and might be able to help. There are links to Gitter, IRC etc listed at the end of this page: https://fishshell.com

**Comment by k4nar** [comment]
This was just merged yesterday :smile: : https://github.com/TailorDev/Watson/pull/239

I'm not sure when we'll make the next release. Could be soon :) .

**Comment by martinklepsch** [comment]
Haha, thanks for pointing me to this, I searched issues but not PRs :) Will close then 👍
