### ISSUE TITLE
Is it safe to just move the frames folder to a Dropbox folder?

### ISSUE THREAD

**Issue by acidjunk** [TailorDev/Watson#245]
I did read some of the other issues in which multiple methods are described to setup a Watson that can be synced between workstations. Setup syncing with with crick.io: works like a charm. Really wonderful stuff :)

Previously I used a tracker with a sqlite file and I just symlinked the sqlite file to a dropbox folder (used it for a year and had 2 conflicts due to a not closed tracker) -> So I'm just wondering : when I copy the frames folder to Dropbox and symlink it : would it work correctly?

**Comment by jmaupetit** [comment]
Hi @acidjunk ! Thank you for your feedback on this project :heart: 

I also used Dropbox with Mackup [1] for years to sync my watson Frames between my laptops. And I can assure you that it works like a charm!

[1] https://github.com/lra/mackup

**Comment by acidjunk** [comment]
Thanks.
