### ISSUE TITLE
Add an option to the remove command to delete all frames

### ISSUE THREAD

**Issue by Th3Mouk** [TailorDev/Watson#25]
Probably a must have to add a command to delete all frames.

**Comment by jmaupetit** [comment]
Thank you for your feedback!

This is potentially dangerous, but it might be useful. So the `remove` command usage would be something like:

    $ watson remove [--all] [FRAME_ID FRAME_ID ...]

Can you please add a new issue for the un-removable last frame bug?

**Comment by k4nar** [comment]
Good idea, I'll work on it :+1: .

**Comment by jmaupetit** [comment]
:+1: thx!

**Comment by k4nar** [comment]
After some thought, this is not a very common use case, so I don't think that a special option or a new command would be useful.

Deleting all the frames is simply a matter of deleting the file `~/.config/watson/frames` (or its equivalent on other OSes), so maybe we could add that in the docs.

**Comment by Th3Mouk** [comment]
It's a good solution too

**Comment by jmaupetit** [comment]
:+1:
