### ISSUE TITLE
Export to csv?

### ISSUE THREAD

**Issue by jimmysjolund** [TailorDev/Watson#256]
I have tried to find out if it's possible to create a csv file of the report, but haven't found any clues. I need to provide time reports on weekly and monthly basis and the most convenient way would be to use a csv file which I can then format to the different needs within the company. Is this possible already and if so, how? Or could it be included in a future version so I would be able to change to Watson for my time tracking?

**Comment by k4nar** [comment]
We already have `watson log --json` & `watson report --csv`, so adding a `--csv` option seems like a great idea :) .

**Comment by davidag** [comment]
@jimmysjolund this has been implemented in #281, any feedback is welcome! :tada: 

@jmaupetit @k4nar should this issue be closed?

**Comment by jmaupetit** [comment]
Yep. We need to release it now!
