### ISSUE TITLE
Add frames from the past

### ISSUE THREAD

**Issue by varac** [TailorDev/Watson#257]
I'd like to add frames from the past, i.e. today I realize that I didn't track a frame from last week.
Sth. like

    watson add --start 2019-03-01T10:10 --stop 2019-03-01T12:30 Project1 +#123

There's already an [PR that would add a relative time to the start command](!224), but for the usecase of adding already ended frame an `add` cmd would be much more useful, since you can track a past frame with only one command.

**Comment by jmaupetit** [comment]
In fact, this command already exists in the `master` branch, but has not been released yet. See: https://github.com/TailorDev/Watson/blob/master/docs/user-guide/commands.md#add

**Comment by varac** [comment]
Oh great! Can you please do a next release ? 1.6.0 is nearly a year old now (2018-04-23).

**Comment by jmaupetit** [comment]
Yeah sorry for that. I'll do this quickly.

**Comment by varac** [comment]
Thanks a lot :1st_place_medal:
