### ISSUE TITLE
Please release a new version (1.6.1? 1.7.0?) of Watson

### ISSUE THREAD

**Issue by mrietveld** [TailorDev/Watson#261]
There are a lot of great new features and some great work that has been done on Watson in the last year. 

However, it's been 11 months since the last release. From what I can see, releases before that happened more frequently. 

Would you mind releasing Watson relatively soon and saving any other planned work for the next release? (Iteration instead of perfection!). 

Thanks!

**Comment by jmaupetit** [comment]
Hi @mrietveld! I heard you loud and clear 😁 I'll do this right now!

**Comment by mrietveld** [comment]
AWESOME! Thank you so much!
