### ISSUE TITLE
Modularize bash.completion

### ISSUE THREAD

**Issue by MaxG87** [TailorDev/Watson#269]
The bash.completion file is, IMHO, a bit badly structured. It consists of only one function where all code is stuffed in. This leads to code duplication (consider the code to auto-complete projects or tags), complicated control flows and deep indentations. I think the file would benefit from a bit of refactoring that would move blocks into their own functions.

However, this kind of refactoring is quite complex and, given the built-in maintainability malus of bash, likely to lead to bugs. One either would have to accept this or to write tests beforehand. While testing bash completion is not straightforward, it seems at least possible (https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash/).

With this issue I want to start a discussion about whether refactoring the completion script is considered to be helpful at all or whether I miss design requirements that make the current design optimal.

So, what do you think about the code quality of bash.completion?

**Comment by jmaupetit** [comment]
I'll support you on this!

**Comment by MaxG87** [comment]
Thank you. I am looking forward to this. However, should we wait for the outcome of #270 before we start here?

**Comment by davidag** [comment]
@MaxG87 just a quick question: given that #270 looks very promising, will this issue still be valid after completing #261 ?

Thank you!

**Comment by MaxG87** [comment]
I think that this issue is irrelevant after #276 got merged. I will be a complete replacement for a manually maintained bash.completion file.
