### ISSUE TITLE
Start a frame with a defined date and time

### ISSUE THREAD

**Issue by lunika** [TailorDev/Watson#28]
Hi,

Most of time I forget to start watson when I start a new task. If I start watson 30 minutes after I start my task, I have to wait the end of the task and then edit the frame and change the date. 

It would be great to have an option like `--date` where you can specify the date and time.

WDYT ?

**Comment by jmaupetit** [comment]
Thank you for your feedback dude :smile_cat:

I have encountered the same situation quite often and I think that an alternative to the `--date` option to the `start` command would be to be able to edit the current session via:

    $ watson edit --current

It would be easier than providing a date time via command line.

@k4nar WDYT?

**Comment by k4nar** [comment]
Yeah, an option to specify the time at which the frame should have started would be cool (a time in the future being illegal).

I don't really see a point to require a full date though, something like `HH:MM` or eventually `HH:MM:SS` would be enough (it could be tricky around midnight but you can still do this the old way and edit the frame).

What would be a good name for that option ? Maybe `-f, --from`.

**Comment by lunika** [comment]
If you use the [iso 8601](https://fr.wikipedia.org/wiki/ISO_8601) notation you don't care if it's a date or a time.

**Comment by jmaupetit** [comment]
@lunika good idea, if we were computers. But we are not :)
@k4nar doing this "the old way" by editing the `state` file (current frame) is not human friendly as the start datetime is a timestamp.

Moreover, the start -f does not cover the scenario where you forgot tags or made a typo in the project name. Do you really prefer this?

```bash
# Oops I forgot to launch watson 30 minutes ago
$ watson start foo -f HH:MM
# Oops I forgot the proper tag
$ watson stop
$ watson delete FRAMEID
$ watson start foo +tag -f HH:MM
```

To this?

```bash
# Oops I forgot to launch watson 30 minutes ago
$ watson start foo
$ watson edit --current
# Add tags, fix start field, etc.
```

**Comment by k4nar** [comment]
Maybe `watson edit` could edit the current frame by default. Right now it edits the last recorded one.

**Comment by jmaupetit** [comment]
:+1:

**Comment by lunika** [comment]
:+1:

**Comment by waynew** [comment]
I can give a :+1: to editing the current frame. That's basically what I think I want to do.

**Comment by SpotlightKid** [comment]
Yes, if there is a running frame, `edit` should to default to this one, instead of the last finished one, IMHO.

**Comment by willdurand** [comment]
:+1:
