### ISSUE TITLE
1.7.0 on Homebrew

### ISSUE THREAD

**Issue by oneWaveAdrian** [TailorDev/Watson#284]
Hey guys, awesome tool!

```
brew update && brew install watson
Already up-to-date.
Warning: watson 1.6.0_1 is already installed and up-to-date
To reinstall 1.6.0_1, run `brew reinstall watson`
```
Any chance you could push the new release to [homebrew](https://brew.sh/) as well?
Would love to use that [aggregate](https://tailordev.github.io/Watson/user-guide/commands/#aggregate) feature!

Thanks!

**Comment by jmaupetit** [comment]
Hey @oneWaveAdrian! My bad, I didn't take time to package our latest release for homebrew...

**Comment by fmitchell** [comment]
Until this is pushed, is there an alternative way to use 1.7.0 (can you force brew to use a tag from a repo) or would i need to uninstall it via brew first, then install it with pip instead?

**Comment by jmaupetit** [comment]
Using `pip` should be the one way to do it IMO. That said, using homebrew makes Watson more fancy to install for non-pythonic Mac users, but it's painful to maintain the corresponding package.

**Comment by oneWaveAdrian** [comment]
@jmaupetit Thanks, I totally forgot to close this!
