### ISSUE TITLE
watson edit throws "fatal: not a git repository (or any of the parent directories): .git"

### ISSUE THREAD

**Issue by fhchl** [TailorDev/Watson#285]
On my machine, whenever I do a watson edit and save+close the edited frame I get a couple of error messages:

```
> watson edit
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```
However, looking at the log, the edits seem to work fine.

I am using watson 1.7.0 on Ubuntu 18.04 with Python 3.7 installed via anaconda and git 2.17.1.

**Comment by davidag** [comment]
Watson relys on `click.edit()` function [(see API)](https://click.palletsprojects.com/en/7.x/api/?highlight=edit#click.edit), which autodetects the editor used to make changes to the json representation of the current frame.

This means that there's probably an issue with your editor configuration. Maybe you're using `vim` and `.vimrc` loads something that expects a `.git` folder to exist?

**Comment by fhchl** [comment]
You are completely right. This seems to be a problem with Sublime Text. Cheers!
