### ISSUE TITLE
Fish Shell completions: `aggregate` is not included

### ISSUE THREAD

**Issue by nesmyslny** [TailorDev/Watson#289]
I noticed that the `aggregate` command is not taken into account in the Fish Shell completions. (I couldn't find any reference of it in https://github.com/TailorDev/Watson/blob/master/watson.fish)

### Steps to reproduce
* Use Fish Shell
* Type `watson ag|` + `Tab` (pipe indicates cursor)
* Expected result: `watson aggregate`
* Actual result: `watson tags`

### Versions
* `watson --version`: 1.7.0
* `fish --version`: 3.0.2

Thanks for this project! :)

**Comment by jmaupetit** [comment]
Thanks for the report! Maybe @andrewmeyer can help on this?

**Comment by andrewmeyer** [comment]
As long as I have a branch open, I'll look for any other missing completions

**Comment by nesmyslny** [comment]
Thanks for fixing this :smiley:

**Comment by jmaupetit** [comment]
Thanks @andrewmeyer :pray:
