### ISSUE TITLE
hourly rate per project?

### ISSUE THREAD

**Issue by ezbik** [TailorDev/Watson#291]
It is worth adding such functionality, so `watson report`  not only returns total time spent, but also does simple multiplication time x hourly-rate . I personally use Watson to bill my customers, so that'd useful. What do you think?

**Comment by k4nar** [comment]
I think that would be a slippery slope :smile: . I think we should focus on time report, rather than accounting or billing.

That being said, one could write a wrapper around watson to add this, thanks to the `--json` flag.

**Comment by jmaupetit** [comment]
I think writing a wrapper around it is a good idea. That said, I also think that it would be great to be able to add plugins to Watson...

**Comment by davidag** [comment]
@jmaupetit With respect to community growth and code sharing, I think plugins might be a better solution than wrapping. Apparently, there are many use cases that go beyond time reporting and tracking (e.g. #249) that could benefit from a plugin architecture.

**Comment by jmaupetit** [comment]
I do agree, but writing a wrapper in the meantime looks like a pragmatic solution. WDYT?

**Comment by davidag** [comment]
Sure @jmaupetit, it seems perfectly reasonable right now :+1:.

Let me add that maybe using a spreadsheet software with the exported Watson raw data could be enough for this case @ezbik (other people have commented this solution too).

My comment was just trying to support the idea of plugins in Watson to deal with more specific usage patterns :relaxed:

**Comment by ezbik** [comment]
The fix/solution can be different -- can there be a metadata per project e.g. key-value storage? Right now the only data associated with a project is its name.
