### ISSUE TITLE
Parsing of date/time fails when using `stop --at`

### ISSUE THREAD

**Issue by nesmyslny** [TailorDev/Watson#292]
I tried to stop a frame at a specific time, including a date:
```
watson stop --at "2019-07-04 09:37:00"
```
This fails with this error message:
> Error: Could not parse time.Please specify in (YYYY-MM-DDT)?HH:MM(:SS)? format.

Or do I use it wrong?  
Let me know if I should provide more details!

**Comment by k4nar** [comment]
I think the correct syntax is `2019-07-04T09:37:00`. You can also use `09:37` for the current day.

**Comment by nesmyslny** [comment]
Thanks @k4nar, that works!  
I wonder if it should be still treated as bug as it doesn't seem consistent with other commands, like [add](https://tailordev.github.io/Watson/user-guide/commands/#add). `add` accept strings like `--from "2018-03-20 12:00:00"`. At least it's confusing and maybe it's worth adding an example to the documentation of [stop](https://tailordev.github.io/Watson/user-guide/commands/#stop)?

Thanks again for the help :)
