### ISSUE TITLE
aggregate calculates wrong time if used with `--current`

### ISSUE THREAD

**Issue by nesmyslny** [TailorDev/Watson#293]
If `aggregate` is used with `--current` and it takes more than the current day into account, the calculation of the current aggregated day is wrong.  
Example:
```sh
$ watson status
Project xy started 2 hours ago (2019.07.04 10:26:45+0200)


$ watson log -dc
Thursday 04 July 2019 (2h 17m 31s)
        current  10:26 to 12:44   2h 17m 31s  xy


$ watson report -dc
Thu 04 July 2019 -> Thu 04 July 2019

xy - 2h 17m 50s


$ watson aggregate -c --from 2019-07-03
Wed 03 July 2019 - 7h 17m 42s
  xy - 7h 17m 42s

Thu 04 July 2019 - 4h 36m 51s
  xy - 4h 36m 51s
```
Expected result of *Thu 04 July 2019*: 2h 17m ??s  
Expected result of *Thu 04 July 2019*: 4h 36m 51s

**Comment by jmkerr** [comment]
The current frame is added once for [every day the report is generated](https://github.com/TailorDev/Watson/blob/master/watson/watson.py#L464).

**Comment by nesmyslny** [comment]
Thanks for looking at it!
