### ISSUE TITLE
Include (or provide an option) to include current frame in reports

### ISSUE THREAD

**Issue by waynew** [TailorDev/Watson#31]
Right now the current frame appears to be excluded from reports. If you have no frames, for instance, and you do this:

    $ watson start fnord
    $ sleep 10; # Just so there's some time
    $ watson report

You'll see that watson does not display anything. I think either it should by default, or you could do something like:

    $ watson report --with-current

Most of the time I want to see how much time I've spent on a project including what I've been working on for the past 3.5 hours. Right now I think the only option is to do something like this:

    $ watson report
    $ watson status

And then manually combine the two numbers. There must be a better way :)

**Comment by jmaupetit** [comment]
Interesting scenario and interesting proposed solution. I give it a :+1:

**Comment by SpotlightKid** [comment]
+1 (but please also provide a short form of the option!)

**Comment by k4nar** [comment]
Shouldn't we have a config option for that? It looks like a personal preference to me.

**Comment by jmaupetit** [comment]
An option is a good idea for defaults, but it must be overridable when calling the `report` command.

**Comment by SpotlightKid** [comment]
A sidenote: as more options are used, it would be good thing to provide a sane wrapper around `ConfigParser` so you don't have to do stupid things like this all the time:

```
option = (watson.config.get('section', 'option')
          if watson.config.has_option('section', 'option') else default)
```

Even if it's only wrapping the above code in sub-classes `get()` method:

```
class SaneConfigParser(ConfigParser):
    def get(self, section, option, default=None):
        return (self.get(section, option)
                if self.has_option(section, option) else default)
```
