### ISSUE TITLE
User guide on the website is not the latest

### ISSUE THREAD

**Issue by hiiwave** [TailorDev/Watson#319]
Under [github.io](http://tailordev.github.io/Watson/user-guide/configuration/#options), the document of options is not the latest.
![image](https://user-images.githubusercontent.com/5608511/65362808-783dad80-dc3b-11e9-8acd-8105305d004e.png)

Comparing to [configuration.md](https://github.com/TailorDev/Watson/blob/master/docs/user-guide/configuration.md#options)

--- 

#### `options.confirm_new_project` (default: `false`)

If `true`, the user will be asked for confirmation before creating a new project. The option can be overriden in the command line with `--confirm-new-project` flag.

#### `options.confirm_new_tag` (default: `false`)

If `true`, the user will be asked for confirmation before creating a new tag. The option can be overriden in the command line with `--confirm-new-tag` flag.

#### `options.date_format` (default: `%Y.%m.%d`)

Globally configure how `dates` should be formatted. All [python's `strftime` directives](http://strftime.org) are supported.

#### `options.log_current` (default: `false`)

If `true`, the output of the `log` command will include the currently running
frame (if any) by default. The option can be overridden on the command line
with the `-c/-C` resp. `--current/--no-current` flags.

---

Maybe you forgot to re-build the doc after #306?

**Comment by jmaupetit** [comment]
Yes, for now, the documentation update is still a manual process usually done after each release, not each merge event. We need to automate this (see #78). Closing this as duplicate.
