### ISSUE TITLE
Please support multiple simultaneous projects

### ISSUE THREAD

**Issue by kseistrup** [TailorDev/Watson#32]
```sh
$ watson start x
Starting x  at 14:49
$ watson start y
Error: Project x is already started.
```
Please enable multiple simultaneous projects.

Cheers.

**Comment by SpotlightKid** [comment]
Do you really want to track times fo two or more projects simultaneously? What would be the semantics of that?

Maybe your needs could be addressed by adding / removing tags to a running projects frame? I.e. a command that would implicitly stop the current frame and immediately start a new one with the same project and different tags? Hypothetical example:

```
$ watson start project1 +activity1
...
$ watson tag activity2
...
$ watson tag -d activity1
```

**Comment by willdurand** [comment]
> Do you really want to track times fo two or more projects simultaneously?
> What would be the semantics of that?

I could not agree more with these two questions. It seems surprising to simultaneously track times for different projects.

**Comment by kseistrup** [comment]
I guess I could lump several projects into a super project and use tags for the projects…

**Comment by k4nar** [comment]
I agree with the concerns raised here. Simultaneous projects seem out of scope for Watson.

Regarding the `tag` command proposed by @SpotlightKid, we could discuss it in another issue, but I find it a bit ambiguous.

**Comment by acidjunk** [comment]
@michaelbeaumont Isn't above use case correctly handled by using tags? (at least that's how I'm using it. Some example of tags I use: 

"frontend" : to track frontend work across projects
"backend: you get the idea
"subsidiary": for hours covered by an R&D fund

etc.

You can tag multiple tags per project/task

**Comment by michaelbeaumont** [comment]
I can't have multiple projects started simultaneously. How would you map my example to your use of tags?

**Comment by acidjunk** [comment]
listening to audio: tag
completing some task: tag
project: whatever

Not sure if it's viable for you.

**Comment by michaelbeaumont** [comment]
Right but how can I track for _which project_ (e.g. `physics` for listening to a lecture) I'm listening to the audio for while I'm completing the task for some _other project_ (e.g. fixing a bug for application `programx`)?

I suppose I could just entirely abandon projects and only use tags and add `+project:_name_` so I'd have:
```
[project:programx]
[project:programx, project:physics] # lecture is turned on but I continue working on my bug
[project:programx] # lecture turned off
```
Feels like I'm really going against the grain though...

**Comment by acidjunk** [comment]
I mostly use it for keeping track of billable hours. So for me, in most cases projects <=> customer. And I can't work on 2 project simultaneously. To keep track of "what" I did in a project I use tags. Downside: tags are shared over all project: but they don't make sense for all projects.

**Comment by jmaupetit** [comment]
IMO the main issue here is: how can you focus on your lecture while fixing a bug! Is this humanly feasible to achieve such thing? I cannot. :sweat_smile:
