### ISSUE TITLE
watson start should not accept empty project

### ISSUE THREAD

**Issue by hiiwave** [TailorDev/Watson#321]
When `options.confirm_new_project` is false, `watson start` gives error when there's no project given.
```
$ watson config options.confirm_new_project false
$ watson start
Error: No project given.
```

However, `watson start` asks if users would like to create empty project when `options.confirm_new_project` is true. This does not look like expected behavior.
```
$ watson config options.confirm_new_project true
$ watson start
Project '' does not exist yet. Create it? [y/N]:
```

**Comment by jmaupetit** [comment]
Thanks for the report and the fix :pray:
