### ISSUE TITLE
Importing frames from different machine

### ISSUE THREAD

**Issue by Tycholiz** [TailorDev/Watson#345]
I have been able to find a `frames` file on my Linux machine, however on the Mac I am unable to find a corresponding file. Is it named differently on Mac? Is there a more convenient way to import frames files?

**Comment by jmaupetit** [comment]
You can import a frame file using the `merge` command [1]. Your frame files is placed in Watson's configuration directory, _e.g._ something like `~/Library/Application Support/watson` for MacOSX [2].

[1] http://tailordev.github.io/Watson/user-guide/commands/#merge
[2] http://tailordev.github.io/Watson/user-guide/configuration/
