### ISSUE TITLE
Group times with the same tag [question]

### ISSUE THREAD

**Issue by buscon** [TailorDev/Watson#347]
I am wondering whether there is a way to group all the time spent on the same tag for a single day.

If I start and stop the same tag more than once in the same day, I have a list of separated log lines. That is ok and good, but it would be nice to have the total amount spent on the same tag for a certain day - or maybe even for more than one day.

I could not find such option in the documentation. If it's not available, I would like to request such feature.

Thank you for the great work.

**Comment by jmaupetit** [comment]
You can use the `log` or `report` command along with the `--tag` option. You may also restrict the time span.

Log command documentation: http://tailordev.github.io/Watson/user-guide/commands/#log

**Comment by buscon** [comment]
Thanks for your answer, but even with such options I still cannot get a sum of  a certain tag that was logged more than once on the same day.

**Comment by jmaupetit** [comment]
Can you provide test data or example output so that we can decide whether its a bug or a misconception of the tool?

**Comment by buscon** [comment]
sure, here is a simple example, where I logged two times on the same project and on the same tag. 
What I would like to know is: what is the total time I spend on the testtag tag?
In my example it is the total time spend on the "testproject" project, because I have only one tag. But if I use more than one tag per project, I do not know how to retrieve such information - apart from calculating it by myself...

$ watson log --project testproject
Thursday 09 January 2020 (07m 06s)
        ae78584  19:15 to 19:22      06m 35s  testproject  [testtag]
        7dd8074  19:22 to 19:23          31s  testproject  [testtag]

**Comment by jmaupetit** [comment]
You must use the `report` command then!

**Comment by buscon** [comment]
ah, thank you! I totally missed that!
