### ISSUE TITLE
start --at

### ISSUE THREAD

**Issue by prat0088** [TailorDev/Watson#352]
After using watson for 3 weeks I've discovered I frequently forget to start timing another task when I switch contexts.  Currently I need to:

1. stop --at
2. start task
3. edit the start time to match the time in 1

I would like:

1. start --at

that would stop the current task as of the --at time, then start a new task as of the --at time... if stop_on_start is set.

**Comment by davidag** [comment]
@prat0088 you can reduce the number of steps using current features:

1. `stop --at`
2. `start -G` (leave no gap)

Nevertheless, your proposal is interesting and I'd probably use it too. Thanks!

**Comment by prat0088** [comment]
Did not realize -G works like that.  Thanks!

**Comment by hellerbenjamin** [comment]
I would use this as well!

**Comment by sseppola** [comment]
Sometimes you forget to start the timer after an intentional gap, `watson start --at` would be great for this scenario.

**Comment by joelostblom** [comment]
I just started using watson and after breaks I keep forgetting to start it until 10-15 min into my task. Maybe I will learn over time, but an `--at` option for `start` would be great!

**Comment by joelostblom** [comment]
For reference, this has also been discussed in issue https://github.com/TailorDev/Watson/issues/75 and PR https://github.com/TailorDev/Watson/pull/224.

**Comment by jmaupetit** [comment]
Hi @joelostblom et al. we heard you loud and clear :wink: Feel free to propose a PR that implements this feature :heart:

**Comment by joelostblom** [comment]
Thanks @jmaupetit ! I created #364.
