### ISSUE TITLE
logged time is lost

### ISSUE THREAD

**Issue by notaduck** [TailorDev/Watson#353]
Hi. I've been using Watson to log the time I've spent on a project. But it looks like it has erased everything from Sunday 19 January 2020 ?!

`watson report`
```
Sunday 26 January 2020 (8h 04m 55s)
        a2a1980  09:25 to 12:52   3h 26m 46s  ulduniverset  [travel]
        799c7a0  12:52 to 15:00   2h 07m 42s  ulduniverset  [meeting]
        f1426c9  15:02 to 15:53      50m 50s  ulduniverset  [meeting]
        de3f8f0  15:53 to 17:33   1h 39m 37s  ulduniverset  [travel]

Monday 20 January 2020 (22m 53s)
        a09fa6f  10:09 to 10:14      04m 39s  ulduniverset  [configuration]
        38401a7  10:20 to 10:39      18m 14s  ulduniverset  [configuration]

```

As you can see it started from the 19. Jan and to 26 Jan. but there is no entry for the 19 Jan?! is there any way to restore that? or is it just lost?

**Comment by davidag** [comment]
Could you try `watson log --month` and see if the there are frames in that date?

**Comment by notaduck** [comment]
@davidag so `watson log --month` actually returned all the correct data!

```
Sunday 26 January 2020 (8h 04m 55s)
        a2a1980  09:25 to 12:52   3h 26m 46s  ulduniverset  [travel]
        799c7a0  12:52 to 15:00   2h 07m 42s  ulduniverset  [meeting]
        f1426c9  15:02 to 15:53      50m 50s  ulduniverset  [meeting]
        de3f8f0  15:53 to 17:33   1h 39m 37s  ulduniverset  [travel]

Monday 20 January 2020 (22m 53s)
        a09fa6f  10:09 to 10:14      04m 39s  ulduniverset  [configuration]
        38401a7  10:20 to 10:39      18m 14s  ulduniverset  [configuration]

Friday 17 January 2020 (1h 02m 02s)
        09ffc81  09:34 to 10:24      49m 47s  ulduniverset  [web_dev]
        3630221  10:48 to 11:00      12m 15s  ulduniverset  [reading_documentation]

Thursday 16 January 2020 (1h 01m 09s)
        1cf6eca  10:41 to 10:44      02m 53s  ulduniverset  [configuration]
        934ba60  10:51 to 11:08      16m 37s  ulduniverset  [configuration]
        90568ac  11:16 to 11:34      18m 13s  ulduniverset  [configuration]
        1e7461c  11:39 to 12:02      23m 26s  ulduniverset  [configuration]

Wednesday 15 January 2020 (7h 18m 00s)
        6045d6f  10:00 to 12:00   2h 00m 00s  ulduniverset  [travel]
        236ba9f  12:30 to 16:00   3h 30m 00s  ulduniverset  [meeting]
        099e1b2  16:30 to 18:18   1h 48m 00s  ulduniverset  [travel]
```

I misspelt the project name once and manually edited the project name `~/.config/watson/frames` could that be the reason?

**Comment by jmaupetit** [comment]
Hi @notaduck :wave: 

Given the output you pasted, it looks like you are using the `log` command (instead of the `report` command).

I invite you to read the documentation of the `report` command:

```
$ watson report --help
```
On-line documentation: http://tailordev.github.io/Watson/user-guide/commands/#report

Relevant part for your issue:

> By default, the time spent the last 7 days is printed. This timespan can be controlled with the --from and --to arguments. The dates must have the format YEAR-MONTH-DAY, like: 2014-05-19.

If you want to report all activity related to a project, you may use:

```
$ watson report --all -p ulduniverset
```

Note that the same options and restrictions apply to the `log` command.

HTH

**Comment by notaduck** [comment]
I missed the `--all -p ulduniverset` -_-
Thanks for the reply both of you!
