### ISSUE TITLE
Total time information

### ISSUE THREAD

**Issue by pylipp** [TailorDev/Watson#356]
I'm looking for a way to obtain total time information of a time period of interest, e.g. the current day.

`watson report --day` outputs a final line about total time of the day's frames, so I could pipe it into `tail -n1`.
However this final line is skipped if only a single project occurred that day (see https://github.com/TailorDev/Watson/blob/master/watson/cli.py#L696 )

Hence the questions:
- Is there a more clever way to obtain total time information of the current day?
- If not; are there objections to remove the condition mentioned above, and always have `watson report` the total time information?

**Comment by jmaupetit** [comment]
I think we are not consistent here, we should always print the total time information. Are you willing to work on it and propose a PR? :pray:
