### ISSUE TITLE
Windows 10 Pro can not use log and report commands

### ISSUE THREAD

**Issue by MindaugasVaitkus2** [TailorDev/Watson#370]
I installed td-watson with "pip install td-watson" command on Windows 10 Pro OS.  I can not from command prompt as administration "watson log" and "watson report" commands. 
I get answer:
C:\Windows\system32
The system cannot find the file specified.
But I can use commands as watson frames and watson projects. 
How to configure or debug?
My path to package c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\watson\

**Comment by k4nar** [comment]
If you have type `start log` or `start project`, you have invoked the `start` command, which is unrelated to Watson. You should be able to do `watson start xxx` or `watson log` instead.

**Comment by MindaugasVaitkus2** [comment]
I used watson start and watson log, I made printing mistake.

**Comment by MinchinWeb** [comment]
@MindaugasVaitkus2 Can you paste the full error message here? I can't reproduce this myself, but the error message should offer some clues.

**Comment by MindaugasVaitkus2** [comment]
C:\Windows\system32>watson log
The system cannot find the file specified.

C:\Windows\system32>watson report
The system cannot find the file specified.

C:\Windows\system32>watson frames
519c9f0
aa8d896
a0d81d5
25b51f4
329a183
f598bb8
1183aff
e8980ca
41bbe0e
fd36dec
2bd1db9

**Comment by MindaugasVaitkus2** [comment]
Here is another error on module. Also tests foders scripts return errors.
C:\Users\User\Documents\GitHub\Watson\scripts>python gen-cli-docs.py
Traceback (most recent call last):
  File "gen-cli-docs.py", line 120, in <module>
    main(commands_md)
  File "gen-cli-docs.py", line 113, in main
    with open(rowsput, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'docs/user-guide/commands.md'

**Comment by mpagels** [comment]
I ran into the same issue.
I started a project, i stopped the project. I can't use watson log or watson status. Same error message.
Any news on this issue?

**Comment by MindaugasVaitkus2** [comment]
I solved problem by reinstalling only python 64 version on my machine. See python.org download version what are the reasons.

**Comment by mpagels** [comment]
Thx for the tip. I did the python installer repair program, but this did not solve the problem. I'm using python 3.7.4

**Comment by MindaugasVaitkus2** [comment]
You have fully reinstall python version. There are two installation packages Windows x86-64 executable installer or Windows x86 executable installer. Depends on processor specifications. You can copy all installed libaries from cmd with pip list and then use pip commands to install bulk all linbraries against. It has to do with Windows files system configuration. See for python versions differences:
https://www.python.org/downloads/windows/

**Comment by mpagels** [comment]
I removed python from my system and installed the latest version. Now it works. Thank you very much.
