### ISSUE TITLE
After edit check doesn't check that the starting time is in the past

### ISSUE THREAD

**Issue by KennethNielsen** [TailorDev/Watson#381]
I just recent made an error while editing an event, where I accidentally set the starting time in the future. I did however not get an error at that time, only when I tried to stop the event did watson complain with:

```
Error: Task cannot end before it starts.
```

It seems like it could be caught already in the after edit-check.

I'm using watson 1.8.0

**Comment by jmaupetit** [comment]
Well spotted @KennethNielsen :pray:

**Comment by KennethNielsen** [comment]
@jmaupetit shall I make a PR for it, or do you prefer to just patch it directly on master?

**Comment by jmaupetit** [comment]
Please, feel free to propose a PR :pray:

**Comment by KennethNielsen** [comment]
@jmaupetit PR ready.
