### ISSUE TITLE
install on Arch prevents for upgrade

### ISSUE THREAD

**Issue by zordsdavini** [TailorDev/Watson#384]
I can't do Arch Linux upgrade because of watson. I very like this app and dont't want to remove it as use it in daily life.

```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing python-arrow (0.15.7-1) breaks dependency 'python-arrow<0.15.6' required by watson
```

Question, can be watson upgraded to newer version for python-arrow?

**Comment by k4nar** [comment]
It was done in https://github.com/TailorDev/Watson/pull/380, but it has not been released yet.

**Comment by jmaupetit** [comment]
We'll make a new release soon!

**Comment by zordsdavini** [comment]
Thanks @k4nar for info. How often is releasing new versions? From release page I see that is about each half year. Lats was month ago. Is it possible that new version will arrive earlier?

**Comment by zordsdavini** [comment]
Arch already waiting for 106 updates that could be applied only after watson new version

**Comment by ybc37** [comment]
If `watson` is the only package depending on `python-arrow` on your system, maybe just exclude the package from the upgrade for now. That being said, [partial upgrades are unsupported](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported), so be sure about it and be aware what you're doing :)

To check what packages depend on `python-arrow`:
```sh
pactree -r python-arrow
# output when only watson depends on it:
# python-arrow
# └─watson
```

To exclude `python-arrow` from upgrades:
```sh
sudo pacman -Syu --ignore='python-arrow'
```

Alternatively, you could try to install the latest development version from git, see https://tailordev.github.io/Watson/#development-version

**Comment by zordsdavini** [comment]
thanks @ybc37 will do upgrade after main work

**Comment by jmaupetit** [comment]
Expect a new release this week. :tada: :rocket:

**Comment by jmaupetit** [comment]
There it is: https://github.com/TailorDev/Watson/releases/tag/1.10.0

**Comment by loonies** [comment]
AUR package updated :clinking_glasses:
