### ISSUE TITLE
"start --at" fails when stopping a current project

### ISSUE THREAD

**Issue by MinchinWeb** [TailorDev/Watson#396]
I'm already running a project, and I want to start a new one but backdate the transition, so I run:

```
watson start New_Project +tagged --at "16:14"
```

and it returns:

```
Stopping project Old_Project [tagged], started 37 minutes ago and stopped just now. (id: 19eb6f0)
Error: Task cannot start before the previous task ends.
```

So it's stopped the current project at the current time, but can't start the new one because then the who projects would overlap.

**Comment by jmaupetit** [comment]
:thinking: that's a tricky one.

**Comment by EdgyEdgemond** [comment]
```
@cli.command()
...
def start(ctx, watson, confirm_new_project, confirm_new_tag, args, at_,
          gap_=True):
   ...
    if (project and watson.is_started and
            watson.config.getboolean('options', 'stop_on_start')):
-        ctx.invoke(stop)
+        ctx.invoke(stop, at_=at_)
```
@MinchinWeb This is the change I made locally to support this. Have put up a PR, but they appear to be stale.

**Comment by MinchinWeb** [comment]
@EdgyEdgemond Thanks so much!
