### ISSUE TITLE
Tab completion not working on Bash or Zsh

### ISSUE THREAD

**Issue by jakevossen5** [TailorDev/Watson#400]
Hey everyone. I would love to be able to use tab to find my projects and such, but tab completion does not seem to be working for me. I searched and found PR https://github.com/TailorDev/Watson/pull/276, but it doesn't seem to be functioning for me. Is there something I need to do to enable / setup tab completion?

Thanks

**Comment by jakevossen5** [comment]
I did some reaching, and I can verify that `/usr/local/share/zsh/site-function` is in `fpath`, `_watson` exists in that directory, and `autoload -Uz compinit && compinit` is in my zshrc

**Comment by flyingdutchman23** [comment]
@jakevossen5 Do the changes of #379 work for you?

**Comment by jakevossen5** [comment]
I don't think so. Tab complete is still suggesting files in my directory, not Watson projects.

**Comment by jmaupetit** [comment]
@jakevossen5 do you use OMZ?

**Comment by jakevossen5** [comment]
If OMZ = Oh my zsh? Then yes.

**Comment by jmaupetit** [comment]
> If OMZ = Oh my zsh? Then yes.

Yes :sweat_smile: 

Have you tried this? https://github.com/TailorDev/Watson/pull/379#issuecomment-754870234

**Comment by jakevossen5** [comment]
That worked! Thank you so much!

**Comment by jmaupetit** [comment]
Ok then, we need to document this.
