### ISSUE TITLE
[question] move configuration and data directory for macOS

### ISSUE THREAD

**Issue by davidwoodburn** [TailorDev/Watson#403]
I'd really like to see the configuration and data directory for macOS moved from `~/Library/Application Support/watson/` to `~/.config/watson/`, just as it is in Linux.

**Comment by jmaupetit** [comment]
This is the default Click behaviour. IMO it's consistent to stick to the system's standard.

**Comment by paulkre** [comment]
I think it would be great if you could specify the data directory because then you would be able to easily push everything to a remote git repo.

**Comment by jmaupetit** [comment]
The application folder is configurable by defining the `$WATSON_DIR` environment variable (see https://tailordev.github.io/Watson/user-guide/configuration/#application-folder).

**Comment by paulkre** [comment]
Thanks, I didn’t know this option existed.
