### ISSUE TITLE
zsh autocompletion doesn't work

### ISSUE THREAD

**Issue by jonasatnewton** [TailorDev/Watson#406]
I love watson so far but the autocompletion in zsh won't work even though I followed the manual, `/usr/local/share/zsh/site-functions` is in my `fpath` and `compinit` is enabled in my zshrc.
With bash I finally got it to work but I had to manually install click and python-dateutil even though I installed Watson via the git repository and `pip3 install -e .`.
About my system: first try was Pop_OS! with omz and the second one with a raspberry pi 3b running raspberry (and also omz installed, eventhough that shouldn have any effect due to the existing path in fpath)
Help would be much appreciated, seems like the error sits as usal in front of the device otherwise the problem prbly hadn't occured twice.

#379 does not help

**Comment by jonasatnewton** [comment]
nvm, see #379

**Comment by jonasatnewton** [comment]
me being dumb closing an existent issue
#379 didn't help

**Comment by jmaupetit** [comment]
Have your tried this? https://github.com/TailorDev/Watson/pull/379#issuecomment-754870234

**Comment by jonasatnewton** [comment]
Yes I did, but it didn't fix the Problem.
