### ISSUE TITLE
A "switch" command 

### ISSUE THREAD

**Issue by Jalkar** [TailorDev/Watson#425]
As a user that switch project often, i would like a switch command
that allow to stop the current project and start the new one in a "one liner"

going from : 
```
watson start prj1 --at 09:00

watson stop --at 12:00
watson start prj2 --at 12:00
```
to

```
watson start prj1 --at 09:00

watson switch prj2 --at 12:00
```

**Comment by jmaupetit** [comment]
You can configure Watson `stop_on_start` / `stop_on_restart` options to do so!

Here is an example from the documentation:

```
$ watson start samourai +pizza +cat
Starting project samourai [pizza, cat] at 11:14
$ watson start jayce +wheeled +warriors
Stopping project samourai [pizza, cat], started 2 minutes ago. (id: d08cdd0)
Starting project jayce [wheeled, warriors] at 11:16
```

Reference documentation: https://tailordev.github.io/Watson/user-guide/configuration/#available-settings
