### ISSUE TITLE
Add addbreak command, to insert a break in a frame

### ISSUE THREAD

**Issue by guglielmo** [TailorDev/Watson#426]
Many times you forget to stop the tracking for a lunch break, or a call, or another interrupting task.

I find it useful to have the possibility of inserting a _break_ (or _interval_) into a frame, effectively splitting the frame into 2 distinct ones.

A break, or interval, is defined only by a start datetime and an end datetime.

```
--------[                A               ]---------->
--------[     A1    ]    BR    [   A2    ]---------->
```

A _break_ `BR` is inserted in frame `A`, dividing it into frames `A1` and `A2`.

The following are true:
- `A1.start_datetime = A.start_datetime`
- `A1.end_datetime = BR.start_datetime`
- `A2.start_datetime = BR.end_datetime`
- `A2.end_datetime = A.end_datetime`
- all other properties pass unchanged from `A` to `A1` and `A2`.
- if A is the current frame, then A2 will become the current frame.

A simpler way to look at this could be to insert a break just by changing the starting datetime of `A`,
and generating a new frame `A1` that is a copy of `A` in the past, up to the beginning of the break.
```
--------[                A               ]---------->
--------[     A1    ]    BR    [   A     ]---------->
```
Then `A` will continnue to be the current frame, and `A1` will be the frame before the break.

Please, consider I am a newbie on Watson, maybe there's already a way to approach this issue.

**Comment by jmaupetit** [comment]
What I usually do in this case is using the `--at` flag of the Watson `start` / `stop` / `restart` commands:

```
$ watson stop --at 12:34
$ watson restart --at 14:02
```

Or a `restart` / `start` (with `stop_on_start` / `stop_on_restart` settings activated) and edit the lunchtime break frame (A1) to change the `stop` date/time.

Do you think it will suit your needs?

**Comment by guglielmo** [comment]
I think this is fit, it's just two commands.
