### ISSUE TITLE
Feature Request: Tab Auto Complete Projects and Tasks

### ISSUE THREAD

**Issue by gutelfuldead** [TailorDev/Watson#427]
Possibility to use tab completion (or something else) to fill in previously used Projects and Tasks. It would prevent misspellings creating unwanted duplicate (and incorrect) projects/tasks.

``watson start <tab>`` would present options for ``project0 project1`` etc. for anything that has already been used and is in the local ~/.config/watson/frames file. 

Once the project is filled in a similar approach to adding tasks IE, ``watson start project0 <tab>`` would present previous tasks for project0 like ``task0 task1`` etc.

Sounds great, maybe not feasible to implement realistically? I'm not sure, Python isn't my forte. I see this is a tall order.

**Comment by jmaupetit** [comment]
Hi @gutelfuldead! You have to set the right completion for your shell, see: https://tailordev.github.io/Watson/#command-line-completion

HTH
