### ISSUE TITLE
Crash caused by ValueError

### ISSUE THREAD

**Issue by Sloff** [TailorDev/Watson#430]
Hi, I'm receiving the following when I try to run Watson on my Windows 10 pc:

```
Traceback (most recent call last):
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ettienne.pitts\AppData\Local\Programs\Python\Python39\Scripts\watson.exe\__main__.py", line 4, in <module>
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\watson\__main__.py", line 1, in <module>
    from watson import cli
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\watson\cli.py", line 529, in <module>
    def report(watson, current, from_, to, projects, tags, ignore_projects,
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\click\decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\watson\cli.py", line 46, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "c:\users\ettienne.pitts\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

**Comment by Wasper256** [comment]
Got the same issue on Ubuntu 20.04LTS. Looks like it happened after python version update(Python 3.8.5) or some other updates in system. 

As a temporary solution I've reinstalled tool on Python 3.6 and it works for me now.

**Comment by jmaupetit** [comment]
Looks like a Click release incompatibility. Which version of Watson are you running? Have you tried to uninstall/reinstall it?

**Comment by Sloff** [comment]
I did a pip install earlier today, so I assume the latest version? How can I confirm?

**Comment by jmaupetit** [comment]
```
watson --version
```

**Comment by Sloff** [comment]
@jmaupetit I only get the error shown above

**Comment by jmaupetit** [comment]
Of course :sweat_smile: Can you point the `pip` release you are using and also the Click release?

```bash
# Get pip release
$ pip --version

# Get click release
$ pip freeze | grep click
```

**Comment by Sloff** [comment]
pip version
```
pip 21.1.1
```

click
```
click==8.0.0
```

**Comment by jmaupetit** [comment]
Hmm, seems that Watson is not compatible with the latest Click major release (from yesterday)... I propose the following as a temporary fix:

```bash
$ pip uninstall click && pip install click==7.1.2
```

**Comment by Sloff** [comment]
Nice, working with the temp fix, thanks @jmaupetit!

**Comment by veganjay** [comment]
Thanks for providing the workaround!

I'm running on Ubuntu 20.04.  In case it is helpful, here's how I set up my workaround env:

I already have a fork of the repo. I obtained it via the following:

    git clone git@github.com:veganjay/Watson.git Watson-veganjay
    cd Watson-veganjay

Update *requirements.txt* to specific click version:

    click==7.1.2

Install via *pipx*:

    pipx install .

**Comment by madeinhaste** [comment]
Hi! I just came across this problem too after doing a system upgrade. I tried to fix it with the following before I found this thread (changes to default argument). Do you think the click compatibility issue likely to be deeper than changing the default argument? Is it safer for me to downgrade click?

```
--- a/watson/cli.py
+++ b/watson/cli.py
@@ -522,3 +522,3 @@ _SHORTCUT_OPTIONS_VALUES = {
               flag_value='plain', mutually_exclusive=['json', 'csv'],
-              multiple=True, default=True, hidden=True,
+              multiple=True, default=['plain'], hidden=True,
               help="Format output in plain text (default)")
@@ -777,3 +777,3 @@ def report(watson, current, from_, to, projects, tags, ignore_projects,
               flag_value='plain', mutually_exclusive=['json', 'csv'],
-              multiple=True, default=True, hidden=True,
+              multiple=True, default=['plain'], hidden=True,
               help="Format output in plain text (default)")
@@ -953,3 +953,3 @@ def aggregate(ctx, watson, current, from_, to, projects, tags, output_format,
               flag_value='plain', mutually_exclusive=['json', 'csv'],
-              multiple=True, default=True, hidden=True,
+              multiple=True, default=['plain'], hidden=True,
               help="Format output in plain text (default)")

```

**Comment by veganjay** [comment]
I suspect that there are additional changes that are needed to be
compatible with the new click.
I did not see any obvious click migration guide, and at the moment I'm a
total click beginner.

With the changes you mentioned, did you try the unit tests, and if so, did
they pass?

Jason

**Comment by jmaupetit** [comment]
Pinning to the latest Click 7 release does the trick, but we need to migrate to click 8 asap!

**Comment by fhuitelec** [comment]
Thanks for the fix :+1:

While working on Click 8 migration, could you release a new version so the fix is live? [@veganjay's solution](https://github.com/TailorDev/Watson/issues/430#issuecomment-841666059) works but is far from ideal (issue & solution discoverability, a latest & stable release is broken).

**Comment by cathos** [comment]
I had the same problem after updating to fedora 35, and then replicated it in an alpine virtual environment. Unfortunately, the new version of click is installed by the fedora package manager, but installing the older version of click with pip works for now, even without specifying the version in the watson build.

**Comment by jmaupetit** [comment]
Should be fixed now! https://github.com/TailorDev/Watson/releases/tag/2.1.0
