### ISSUE TITLE
Watson not found in iMac after install -- Help Needed

### ISSUE THREAD

**Issue by heidobito** [TailorDev/Watson#46]
$ pip install td-watson
Requirement already satisfied (use --upgrade to upgrade): td-watson in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Click in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from td-watson)
Requirement already satisfied (use --upgrade to upgrade): arrow in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from td-watson)
Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from td-watson)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from arrow->td-watson)
zsh: command not found: battery_time_remaining
zsh: command not found: battery_pct_prompt

$ watson help
zsh: command not found: watson
zsh: command not found: battery_time_remaining
zsh: command not found: battery_pct_prompt

**Comment by jmaupetit** [comment]
Please could you provide the following commands output:

```bash
$ echo $PATH
$ which pip
$ which python
```

**Comment by waynew** [comment]
You also may try this:

    $ python -m pip install td-watson
    $ python -m watson status

**Comment by heidobito** [comment]
Thank you ver y much.  I did not have Pip.  Now it works!  I'll try it now.

**Comment by jmaupetit** [comment]
Enjoy watson and give us feedback!
