### ISSUE TITLE
Command to transition between projects and/or tags

### ISSUE THREAD

**Issue by addisonklinke** [TailorDev/Watson#461]
Often I find myself in the following pattern

```
watson start work +project

... some time later

watson stop
watson start personal +lunch
```

This immediate transition of one project (or set of tags) into another seems like it could be easily combined into a single command. This way the above would get replaced with 

```
watson start work +project
watson transition personal +lunch
```

The `transition` command should support the same flags such as `--at` (i.e. if you forgot to stop your work project before heading to lunch, you could mark the transition at some point in the past once you return)

**Comment by jmaupetit** [comment]
Hi @addisonklinke :wave: 

By setting the `stop_on_start` option to `true` in your configuration file, you can use the following:

```
watson start work +project
watson start personal +lunch
```

And the second `start` command will stop the previous task. Pretty neat, huh?

You will find more information in the settings documentation: https://tailordev.github.io/Watson/user-guide/configuration/#available-settings

HTH.

**Comment by jmaupetit** [comment]
It should be feasible to add such support. Can you declare a new issue for this specific feature request or better: propose a PR? :pray: :muscle: :heart:

**Comment by addisonklinke** [comment]
It looks like the backend is written in Python. Could you provide some guidance on the general structure/framework and where to start?
