### ISSUE TITLE
Is there a way to resume (if frame has been accidentally stopped)?

### ISSUE THREAD

**Issue by lukas-conlance** [TailorDev/Watson#467]
I'd like to resume the previous frame instead of creating a new one. Is this possible?

**Comment by jmaupetit** [comment]
Hi @lukas-conlance :wave: 

Unfortunately, there is no builtin command to resume a stopped frame, but, in this case, you can edit the previous frame once done and update the end date/time to its current value using the `watson edit` command.

Having a `--no-gap` option to the `restart` command would have helped, but it is not implemented yet.

If you have time to add such option to Watson, your contribution would be warmly welcome! :heart: :pray:

Closing this issue and adding the feature request flag. Feel free to re-open it.
