### ISSUE TITLE
[feature request] watson switch

### ISSUE THREAD

**Issue by thiborose** [TailorDev/Watson#483]
I think a missing feature that would save a lot of time is **watson switch**: 

```bash
watson start projectA
> Starting project projectA at 10:00

# 1h later
watson switch projectB 
> Stopping project projectA , started 1 hours ago and stopped just now. (id: xxxxx)
> Starting project projectB at 11:00
```

It would be great to be able to specify a timestamp in the past: 

```bash
watson start projectA # now is 10AM
> Starting project projectA at 10:00

# 1h later
watson switch projectB --at 10:30 
> Stopping project projectA , started 1 hours ago and stopped 30min ago. (id: xxxxx)
> Starting project projectB at 10:30
```

It would basically be a combination of _watson stop_ and _watson start_. As this is a very common and repetitive pattern, I think I'd be great to have this switch command.

**Comment by jmaupetit** [comment]
Hi @psawa :wave: 

There is a trick to achieve the same feature: once properly configured, you can use the `start` command to stop the on-going frame and start a new one. To do so, set the `stop_on_start` option to `true` [1].

And thanks to @EdgyEdgemond we are also able to `start --at` a new working session (see #480). Note that it has not been released yet.

[1] https://tailordev.github.io/Watson/user-guide/configuration/#optionsstop_on_start-default-false
