### ISSUE TITLE
report, aggregate 

### ISSUE THREAD

**Issue by scriptor-pro** [TailorDev/Watson#506]
using report, log or aggregate, Watson provides me no way to use the command line again except by exiting. I'm runnning MX Linux 21 (with systemd if it helps). 

![watson-report-bug](https://github.com/TailorDev/Watson/assets/64631542/61f8ae5e-787a-4727-9111-dd34d4a30c27)

**Comment by ericguirbal** [comment]
Watson uses a pager by default. Press key `q` to quit or `h` for help. To disable it, run command `report`, `log` or `aggregate` with option `-G`, or edit your configuration file with `watson config --edit` or  `watson config options.pager false`.
