### ISSUE TITLE
[restart command] stop_on_start option?

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#57]
It seems that the `stop_on_start` option is not taken into account when using `restart` with an active project. In the following scenario, should we consider stopping `bar` and restart `foo`?

```
$ watson start foo +tag
$ watson start bar +lol
Stopping project foo [tag], started just now. (id: xxxxxx)
Starting project bar [lol] at 13:48
$ watson restart
Error: Project already started: bar [lol]
```

**Comment by k4nar** [comment]
I'm not sure to see why you would want to do that. But yeah it would be more coherent.

**Comment by SpotlightKid** [comment]
There is an extra option `stop_on_restart`. This was specifically added, because it would be semantically surprising, if the `restart` command stopped something without being explicitly asked for it.

**Comment by k4nar** [comment]
Oh right I forgot about it :) .

**Comment by SpotlightKid** [comment]
Restarting the previous project is possible with `watson restart -s -- -2`.

**Comment by jmaupetit** [comment]
Thank you for this explanation @SpotlightKid. I will consider this issue as solved.
