### ISSUE TITLE
Switch from git-flow to a simple git branching model

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#58]
Historically at TailorDev we used to be [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) people. This is why you will find multiple branches in this repository, e.g. `master`, `develop`, and feature branches (`feature/foo`). As previously mentioned by @willdurand and after a few weeks working with [a simple git branching model](https://gist.github.com/jbenet/ee6c9ac48068889b0912), I think we need to clean up this repository and only keep the `master` branch. Every feature or hotfix will be developed in a feature branch and merged to master. All tags should point to `master` commits.

If we do so, this will have consequences for people having forked this repository since we will force push master and remove develop.

Are you ready for this?

**Comment by willdurand** [comment]
Force pushing on master is not mandatory. For forks, it is not a real issue since patchs should still apply. The issue is with PRs as you cannot change the target branch.

Anyway, I appreciate this.

**Comment by k4nar** [comment]
I don't have any strong feeling about this, so go ahead :) .

**Comment by jmaupetit** [comment]
To simplify branching model, here is what I did:

* `master` branch has been merged into `develop`
* original `master` branch has been deleted
* `develop` has been renamed `master`

By doing so, all PR have been closed.

* @SpotlightKid I will finish #53 and will merge this to `master`
* @waynew please can you please re-open #52 and point it to master?
* @larsborn same idea with #63

I hope this will not be too painful, but it had to be done.

**Comment by waynew** [comment]
I've kind of lost interest in #52 - but if anyone is interested in picking up where I left off they're more than welcome :) And I'll be happy to answer any questions they might have.

**Comment by larsborn** [comment]
I rebased as you wished. Will continue work in #74.

@waynew what was the exact intention? Maybe I can take over.

**Comment by waynew** [comment]
@larsborn #52 is a good starting place.

Basically I wanted an easy way to say, "How much more time do I have to work this week?" so I added a progress bar. I also wanted a shortcut for less typing for the workweek command. `watson workweek` was so much more of a pain to type than `watson ww` :wink:
