### ISSUE TITLE
Post edition summary should be converted to local time

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#60]
When editing a frame, post edition summary datetimes are represented as utc and not local times. See for example:

```bash
$ watson status
Project crick [watson, community, tailordev] started 7 minutes ago (2015.11.24 09:27:46+0100)
# Edit the current frame without changing anything
$ watson edit
Edited frame for project crick [watson, community, tailordev], from 08:27 to - (-)
```

**Comment by SpotlightKid** [comment]
Should be a two line fix in [cli.py](https://github.com/TailorDev/Watson/blob/develop/watson/cli.py#L695).

**Comment by jmaupetit** [comment]
Yup. Just a simple reminder for the `1.2.0` roadmap :)
