### ISSUE TITLE
Rename project / tag

### ISSUE THREAD

**Issue by larsborn** [TailorDev/Watson#62]
is there anything planed to rename a project / tag? At the moment I'm doing this with search&replace on the frames file directly (which is possible but most probably not indented ;-)).

I may also be able to contribute with a PR if we agree on a syntax.

    watson rename --project old_project new_project
    watson rename --tag old_tag new_tag

would be a first simple approach. At a later point, we could also integrate some sort of interactivity to ask on a per entry basis for renames.

Or am I heading in a wrong direction since there already is such a command or something?

awesome tool btw :+1:!

**Comment by k4nar** [comment]
That's a great idea. It would make reorganizing your projects or merging them a whole lot easier.

Your proposed syntax seems fine to me.

@jmaupetit : WDYT?

**Comment by jmaupetit** [comment]
:+1: would be really useful.
Thank you for this!

**Comment by SpotlightKid** [comment]
Fixed in #74.
