### ISSUE TITLE
Add project documentation

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#68]
A real browsable documentation is drastically missing. I mean the README is a good start, but it's not enough: for example, all supported configuration options are not documented!

**Comment by jmaupetit** [comment]
As we will only maintain the sphinx documentation, the README file will no longer be a duplicate of `cli.py` docstrings.

**Comment by k4nar** [comment]
That would be very great.

**Comment by jmaupetit** [comment]
To ease our life, we moved to mkdocs (see #77). I will rename this issue.

**Comment by willdurand** [comment]
Fixed?

**Comment by k4nar** [comment]
The PR is not merged yet. I'll review it asap.

**Comment by jmaupetit** [comment]
Thank you @k4nar !

**Comment by jmaupetit** [comment]
Fixed since 1.3.1
