### ISSUE TITLE
Bash completion doesn't handle projects or tags with spaces properly

### ISSUE THREAD

**Issue by SpotlightKid** [TailorDev/Watson#89]
Just noticed this:

```
$ watson start "World Domination" +"first analysis"
$ watson stop
```
now:

```
$ watson start <tab>
anotherproject Domination foo World
...
$ watson start "World Domination" <TAB>
analysis +anothertag first +yetanothertag
...
```

Probably can be fixed by introducing proper quoting for the output of `watson projects` and `watson tags`. Have to look into it.

**Comment by jmaupetit** [comment]
Yes, I also noticed that, and should have reported it later. Thank you for this.
