### ISSUE TITLE
Add contrib directory

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/Watson#95]
As community contributions are growing (:heart: :heart: :heart:), it would be nice to move this work in a `contrib` directory:

```
.
└── contrib
    ├── watson.bash-completion
    ├── watson.bashrc
    └── watson.zsh-completion
```

WDYT?

**Comment by SpotlightKid** [comment]
Not so sure. Having a "contrib" directory may be seen as a message from the project maintainers signalling "here's some code I ship with my project, but it's not mine and I don't maintain (or care) for it". I've seen many examples where code in a "contrib" directory quickly becomes stale or non-functional.

IMHO, you should either accept code into the repository and thereby make it truly part of the project and accept responsibility for it, or reject it. Contributors can still maintain their code in their own repositories and there could be a documentation section, where references to these external contributions can be listed.

**Comment by jmaupetit** [comment]
👍
